'use client'
import {useEffect,useMemo,useState} from 'react'
const money=n=>Number(n||0).toLocaleString('tr-TR',{minimumFractionDigits:2,maximumFractionDigits:2})+' ₺'
const iso=d=>d.toISOString().slice(0,10)
export default function CanteenModule({supabase,students=[],profiles=[],session}){
 const [tab,setTab]=useState('kasa'),[accounts,setAccounts]=useState([]),[products,setProducts]=useState([]),[tx,setTx]=useState([]),[q,setQ]=useState(''),[student,setStudent]=useState(''),[amount,setAmount]=useState(''),[saleAmount,setSaleAmount]=useState(''),[saleNote,setSaleNote]=useState('Manuel kantin satışı'),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false),[from,setFrom]=useState(iso(new Date(Date.now()-6*86400000))),[to,setTo]=useState(iso(new Date())),[prod,setProd]=useState({name:'',category:'Genel',sale_price:'',cost_price:'',stock:'',min_stock:''})
 const load=async()=>{const [a,p,t]=await Promise.all([supabase.from('canteen_accounts').select('*'),supabase.from('canteen_products').select('*').order('name'),supabase.from('canteen_transactions').select('*').order('created_at',{ascending:false}).limit(1000)]);setAccounts(a.data||[]);setProducts(p.data||[]);setTx(t.data||[])}
 useEffect(()=>{load()},[])
 const sm=useMemo(()=>Object.fromEntries(students.map(s=>[s.id,(s.first_name+' '+s.last_name).trim()])),[students]),pm=useMemo(()=>Object.fromEntries(profiles.map(p=>[p.id,p.full_name||'Kullanıcı'])),[profiles])
 const bal=id=>Number(accounts.find(a=>a.student_id===id)?.balance||0),filtered=students.filter(s=>(sm[s.id]||'').toLocaleLowerCase('tr').includes(q.toLocaleLowerCase('tr')))
 const rangeTx=tx.filter(x=>{const d=x.created_at?.slice(0,10);return d>=from&&d<=to&&!x.voided}),rangeSales=rangeTx.filter(x=>['sale','debit'].includes(x.transaction_type)).reduce((a,x)=>a+Number(x.amount),0),rangeCredit=rangeTx.filter(x=>x.transaction_type==='credit').reduce((a,x)=>a+Number(x.amount),0)
 const totalBal=accounts.reduce((a,x)=>a+Number(x.balance),0),debt=accounts.reduce((a,x)=>a+Math.min(0,Number(x.balance)),0),quick=Array.from({length:30},(_,i)=>(i+1)*5)
 async function rpc(name,args,ok){setBusy(true);setMsg('');const {error}=await supabase.rpc(name,args);setBusy(false);setMsg(error?error.message:ok);if(!error)await load();return !error}
 async function credit(e){e?.preventDefault();if(!student)return setMsg('Önce öğrenci seçin.');const v=Number(amount);if(v<=0)return setMsg('Geçerli tutar girin.');if(await rpc('canteen_add_credit',{p_student:student,p_amount:v,p_description:'Bakiye yükleme'},'Bakiye başarıyla yüklendi.'))setAmount('')}
 async function manualSale(v){if(!student)return setMsg('Satış için önce öğrenci seçin.');v=Number(v);if(v<=0)return setMsg('Satış tutarı girin.');if(await rpc('canteen_manual_sale',{p_student:student,p_amount:v,p_description:saleNote||'Manuel kantin satışı'},money(v)+' satış bakiyeden düşüldü.'))setSaleAmount('')}
 async function reverse(x){const reason=prompt('İşlemi geri alma sebebi:','Yanlış işlem');if(reason===null)return;if(confirm(money(x.amount)+' tutarındaki işlem geri alınacak. Emin misiniz?'))await rpc('canteen_reverse_transaction',{p_transaction:x.id,p_reason:reason},'İşlem geri alındı ve bakiye düzeltildi.')}
 async function quickSale(id){if(!student)return setMsg('Önce öğrenci seçin.');const p=products.find(x=>x.id===id);if(!p)return;await manualSale(Number(p.sale_price))}
 async function addProduct(e){e.preventDefault();const payload={...prod,sale_price:Number(prod.sale_price||0),cost_price:Number(prod.cost_price||0),stock:Number(prod.stock||0),min_stock:Number(prod.min_stock||0),created_by:session.user.id};const {error}=await supabase.from('canteen_products').insert(payload);setMsg(error?error.message:'Ürün eklendi.');if(!error){setProd({name:'',category:'Genel',sale_price:'',cost_price:'',stock:'',min_stock:''});load()}}
 function preset(days){const t=new Date(),f=new Date();f.setDate(t.getDate()-days+1);setFrom(iso(f));setTo(iso(t))}
 return <div className="canteenPro">
 <div className="canteenHead"><div><small>E-GÖLKENT · YETKİLİ MALİ MODÜL</small><h2>Kantin Yönetimi</h2><p>Satış, öğrenci bakiyesi, stok, hasılat ve denetim kayıtları.</p></div><button onClick={load}>↻ Yenile</button></div>
 <div className="canteenStats"><div><span>Seçili Tarih Hasılatı</span><b>{money(rangeSales)}</b></div><div><span>Seçili Tarih Yükleme</span><b>{money(rangeCredit)}</b></div><div><span>Toplam Bakiye</span><b>{money(totalBal)}</b></div><div><span>Eksi Bakiye</span><b>{money(Math.abs(debt))}</b></div><div><span>İşlem Sayısı</span><b>{rangeTx.length}</b></div></div>
 <div className="dateFilter"><b>Hasılat Filtresi</b><button onClick={()=>preset(1)}>Bugün</button><button onClick={()=>preset(7)}>Son 7 Gün</button><button onClick={()=>preset(30)}>Son 30 Gün</button><label>Başlangıç <input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Bitiş <input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div>
 <div className="canteenTabs">{[['kasa','Satış / Hızlı Kasa'],['bakiye','Öğrenci Bakiyeleri'],['urun','Ürün & Stok'],['hareket','İşlem Geçmişi']].map(x=><button key={x[0]} className={tab===x[0]?'active':''} onClick={()=>setTab(x[0])}>{x[1]}</button>)}</div>{msg&&<div className="msg">{msg}</div>}
 {tab==='kasa'&&<><div className="cashierStudent"><input placeholder="Öğrenci ara…" value={q} onChange={e=>setQ(e.target.value)}/><select value={student} onChange={e=>setStudent(e.target.value)}><option value="">Satış yapılacak öğrenciyi seçiniz</option>{filtered.map(s=><option key={s.id} value={s.id}>{sm[s.id]}</option>)}</select>{student&&<div className={'cashierBalance '+(bal(student)<0?'negative':'')}><span>{sm[student]} · Bakiye</span><b>{money(bal(student))}</b></div>}</div>
 <div className="salePanel"><section><h3>Hızlı Tutar Satışı</h3><p>Butona dokunduğunuz tutar öğrencinin bakiyesinden anında düşer.</p><div className="quickAmounts">{quick.map(v=><button key={v} disabled={busy||!student} onClick={()=>manualSale(v)}>{v} ₺</button>)}</div></section><section className="manualSale"><h3>Serbest Tutar</h3><p>150 ₺ üzeri veya farklı tutarlı satışlar için.</p><input type="number" min=".01" step=".01" value={saleAmount} onChange={e=>setSaleAmount(e.target.value)} placeholder="Satış tutarı"/><input value={saleNote} onChange={e=>setSaleNote(e.target.value)} placeholder="Açıklama"/><button className="primary" disabled={busy||!student} onClick={()=>manualSale(saleAmount)}>Satışı Yap ve Bakiyeden Düş</button><hr/><h3>Bakiye Yükle</h3><form onSubmit={credit} className="inlineMoney"><input type="number" min=".01" step=".01" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Yüklenecek tutar"/><button disabled={busy||!student}>+ Yükle</button></form></section></div>
 {products.length>0&&<section className="panel"><h3>Ürünle Hızlı Satış</h3><div className="productTiles">{products.filter(p=>p.active).map(p=><button key={p.id} disabled={busy||!student||Number(p.stock)<=0} onClick={()=>quickSale(p.id)}><b>{p.name}</b><span>{money(p.sale_price)}</span><small>Stok: {p.stock}</small></button>)}</div></section>}</>}
 {tab==='bakiye'&&<div className="tableWrap"><table><thead><tr><th>Öğrenci</th><th>Bakiye</th><th>Durum</th></tr></thead><tbody>{students.map(s=><tr key={s.id}><td>{sm[s.id]}</td><td className={bal(s.id)<0?'negative':''}>{money(bal(s.id))}</td><td>{bal(s.id)<0?'BORÇLU':'AKTİF'}</td></tr>)}</tbody></table></div>}
 {tab==='urun'&&<div className="canteenGrid"><section><h3>Yeni Ürün</h3><form onSubmit={addProduct} className="stack">{['name','category','sale_price','cost_price','stock','min_stock'].map(k=><input key={k} required={k==='name'} type={k.includes('price')||k.includes('stock')?'number':'text'} step=".01" placeholder={{name:'Ürün adı',category:'Kategori',sale_price:'Satış fiyatı',cost_price:'Maliyet',stock:'Başlangıç stoku',min_stock:'Minimum stok'}[k]} value={prod[k]} onChange={e=>setProd({...prod,[k]:e.target.value})}/>)}<button>Ürünü Kaydet</button></form></section><section><h3>Stok Durumu</h3><div className="tableWrap"><table><thead><tr><th>Ürün</th><th>Fiyat</th><th>Stok</th></tr></thead><tbody>{products.map(p=><tr key={p.id}><td>{p.name}<small>{p.category}</small></td><td>{money(p.sale_price)}</td><td className={Number(p.stock)<=Number(p.min_stock)?'negative':''}>{p.stock}</td></tr>)}</tbody></table></div></section></div>}
 {tab==='hareket'&&<div className="tableWrap"><table><thead><tr><th>Tarih</th><th>Öğrenci</th><th>İşlemi Yapan</th><th>İşlem</th><th>Açıklama</th><th>Tutar</th><th></th></tr></thead><tbody>{tx.filter(x=>x.created_at?.slice(0,10)>=from&&x.created_at?.slice(0,10)<=to).map(x=><tr key={x.id} className={x.voided?'voidedRow':''}><td>{new Date(x.created_at).toLocaleString('tr-TR')}</td><td>{sm[x.student_id]||'—'}</td><td><b>{pm[x.recorded_by]||'Bilinmiyor'}</b></td><td>{x.voided?'GERİ ALINDI':x.transaction_type==='credit'?'YÜKLEME':'SATIŞ'}</td><td>{x.description||'—'}{x.void_reason&&<small>İptal: {x.void_reason}</small>}</td><td>{money(x.amount)}</td><td>{!x.voided&&<button className="danger compact" disabled={busy} onClick={()=>reverse(x)}>Geri Al</button>}</td></tr>)}</tbody></table></div>}
 </div>
