'use client'
import {useEffect,useMemo,useState} from 'react'
const money=n=>Number(n||0).toLocaleString('tr-TR',{minimumFractionDigits:2,maximumFractionDigits:2})+' ₺'
export default function CanteenModule({supabase,students=[],session}){
 const [tab,setTab]=useState('kasa'),[accounts,setAccounts]=useState([]),[products,setProducts]=useState([]),[tx,setTx]=useState([]),[sales,setSales]=useState([]),[q,setQ]=useState(''),[student,setStudent]=useState(''),[amount,setAmount]=useState(''),[msg,setMsg]=useState(''),[prod,setProd]=useState({name:'',category:'Genel',sale_price:'',cost_price:'',stock:'',min_stock:''})
 const load=async()=>{const [a,p,t,s]=await Promise.all([supabase.from('canteen_accounts').select('*'),supabase.from('canteen_products').select('*').order('name'),supabase.from('canteen_transactions').select('*').order('created_at',{ascending:false}).limit(100),supabase.from('canteen_sales').select('*').order('created_at',{ascending:false}).limit(100)]);setAccounts(a.data||[]);setProducts(p.data||[]);setTx(t.data||[]);setSales(s.data||[])}
 useEffect(()=>{load()},[])
 const sm=useMemo(()=>Object.fromEntries(students.map(s=>[s.id,(s.first_name+' '+s.last_name).trim()])),[students])
 const bal=id=>Number(accounts.find(a=>a.student_id===id)?.balance||0)
 const today=new Date().toISOString().slice(0,10),todayTx=tx.filter(x=>x.created_at?.slice(0,10)===today&&!x.voided)
 const credits=todayTx.filter(x=>x.transaction_type==='credit').reduce((a,x)=>a+Number(x.amount),0),spent=todayTx.filter(x=>x.transaction_type==='sale'||x.transaction_type==='debit').reduce((a,x)=>a+Number(x.amount),0)
 const totalBal=accounts.reduce((a,x)=>a+Number(x.balance),0),debt=accounts.reduce((a,x)=>a+Math.min(0,Number(x.balance)),0)
 async function credit(e){e.preventDefault();if(!student||Number(amount)<=0)return;const old=bal(student),val=Number(amount);let er=(await supabase.from('canteen_accounts').upsert({student_id:student,balance:old+val,updated_at:new Date().toISOString()})).error;if(!er)er=(await supabase.from('canteen_transactions').insert({student_id:student,transaction_type:'credit',amount:val,description:'Bakiye yükleme',recorded_by:session.user.id})).error;setMsg(er?er.message:'Bakiye başarıyla yüklendi.');if(!er){setAmount('');load()}}
 async function quickSale(id){if(!student)return setMsg('Önce öğrenci seçin.');const p=products.find(x=>x.id===id),val=Number(p.sale_price);if(!p||val<=0)return;const old=bal(student);const {data:s,error}=await supabase.from('canteen_sales').insert({student_id:student,total:val,recorded_by:session.user.id}).select('id').single();if(error)return setMsg(error.message);let er=(await supabase.from('canteen_sale_items').insert({sale_id:s.id,product_id:p.id,product_name:p.name,quantity:1,unit_price:val,line_total:val})).error;if(!er)er=(await supabase.from('canteen_accounts').upsert({student_id:student,balance:old-val,updated_at:new Date().toISOString()})).error;if(!er)er=(await supabase.from('canteen_transactions').insert({student_id:student,transaction_type:'sale',amount:val,description:p.name,reference_id:s.id,recorded_by:session.user.id})).error;if(!er)await supabase.from('canteen_products').update({stock:Number(p.stock)-1,updated_at:new Date().toISOString()}).eq('id',p.id);setMsg(er?er.message:p.name+' satışı tamamlandı.');load()}
 async function addProduct(e){e.preventDefault();const payload={...prod,sale_price:Number(prod.sale_price||0),cost_price:Number(prod.cost_price||0),stock:Number(prod.stock||0),min_stock:Number(prod.min_stock||0),created_by:session.user.id};const {error}=await supabase.from('canteen_products').insert(payload);setMsg(error?error.message:'Ürün eklendi.');if(!error){setProd({name:'',category:'Genel',sale_price:'',cost_price:'',stock:'',min_stock:''});load()}}
 const filtered=students.filter(s=>(sm[s.id]||'').toLocaleLowerCase('tr').includes(q.toLocaleLowerCase('tr')))
 return <div className="canteenPro">
  <div className="canteenHead"><div><small>E-GÖLKENT · MALİ İŞLEMLER</small><h2>Kantin Yönetimi</h2><p>Öğrenci bakiyesi, hızlı satış, stok ve mali hareketler tek merkezde.</p></div><button onClick={load}>↻ Verileri Yenile</button></div>
  <div className="canteenStats"><div><span>Bugün Yüklenen</span><b>{money(credits)}</b></div><div><span>Bugün Satış</span><b>{money(spent)}</b></div><div><span>Toplam Öğrenci Bakiyesi</span><b>{money(totalBal)}</b></div><div><span>Eksi Bakiye</span><b>{money(Math.abs(debt))}</b></div><div><span>Aktif Ürün</span><b>{products.filter(x=>x.active).length}</b></div></div>
  <div className="canteenTabs">{[['kasa','Hızlı Kasa'],['bakiye','Öğrenci Bakiyeleri'],['urun','Ürün & Stok'],['hareket','İşlem Geçmişi']].map(x=><button className={tab===x[0]?'active':''} onClick={()=>setTab(x[0])}>{x[1]}</button>)}</div>
  {msg&&<div className="msg">{msg}</div>}
  {tab==='kasa'&&<div className="canteenGrid"><section><h3>Öğrenci Seç</h3><input placeholder="Öğrenci ara…" value={q} onChange={e=>setQ(e.target.value)}/><select value={student} onChange={e=>setStudent(e.target.value)}><option value="">Öğrenci seçiniz</option>{filtered.map(s=><option value={s.id}>{sm[s.id]}</option>)}</select>{student&&<div className={'bigBalance '+(bal(student)<0?'negative':'')}><span>Güncel Bakiye</span><b>{money(bal(student))}</b></div>}<form onSubmit={credit}><label>Bakiye Yükle</label><div className="inlineMoney"><input type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Tutar"/><button>+ Yükle</button></div></form></section><section><h3>Hızlı Satış</h3><div className="productTiles">{products.filter(p=>p.active).map(p=><button disabled={Number(p.stock)<=0} onClick={()=>quickSale(p.id)}><b>{p.name}</b><span>{money(p.sale_price)}</span><small>Stok: {p.stock}</small></button>)}</div></section></div>}
  {tab==='bakiye'&&<div className="tableWrap"><table><thead><tr><th>Öğrenci</th><th>Bakiye</th><th>Durum</th></tr></thead><tbody>{students.map(s=><tr><td>{sm[s.id]}</td><td className={bal(s.id)<0?'negative':''}>{money(bal(s.id))}</td><td>{bal(s.id)<0?'BORÇLU':'AKTİF'}</td></tr>)}</tbody></table></div>}
  {tab==='urun'&&<div className="canteenGrid"><section><h3>Yeni Ürün</h3><form onSubmit={addProduct} className="stack">{['name','category','sale_price','cost_price','stock','min_stock'].map(k=><input required={k==='name'} type={k.includes('price')||k.includes('stock')?'number':'text'} step="0.01" placeholder={{name:'Ürün adı',category:'Kategori',sale_price:'Satış fiyatı',cost_price:'Maliyet',stock:'Başlangıç stoku',min_stock:'Minimum stok'}[k]} value={prod[k]} onChange={e=>setProd({...prod,[k]:e.target.value})}/>)}<button>Ürünü Kaydet</button></form></section><section><h3>Stok Durumu</h3><div className="tableWrap"><table><thead><tr><th>Ürün</th><th>Fiyat</th><th>Stok</th></tr></thead><tbody>{products.map(p=><tr><td>{p.name}<small>{p.category}</small></td><td>{money(p.sale_price)}</td><td className={Number(p.stock)<=Number(p.min_stock)?'negative':''}>{p.stock}</td></tr>)}</tbody></table></div></section></div>}
  {tab==='hareket'&&<div className="tableWrap"><table><thead><tr><th>Tarih</th><th>Öğrenci</th><th>İşlem</th><th>Açıklama</th><th>Tutar</th></tr></thead><tbody>{tx.map(x=><tr><td>{new Date(x.created_at).toLocaleString('tr-TR')}</td><td>{sm[x.student_id]||'—'}</td><td>{x.transaction_type}</td><td>{x.description||'—'}</td><td>{money(x.amount)}</td></tr>)}</tbody></table></div>}
 </div>
}