'use client'
import {useEffect,useMemo,useState} from 'react'
export default function DepartedStudentsModule({supabase,students=[],classes=[],profile,permissions,onRefresh}){
 const [items,setItems]=useState([]),[q,setQ]=useState(''),[restore,setRestore]=useState(null),[msg,setMsg]=useState('')
 useEffect(()=>{supabase.from('student_departures').select('*').order('departure_date',{ascending:false}).then(({data})=>setItems(data||[]))},[])
 const [archiveStudents,setArchiveStudents]=useState([]);useEffect(()=>{supabase.from('students').select('*').in('student_status',['graduated','departed']).then(({data})=>setArchiveStudents(data||[]))},[]);const sm=useMemo(()=>Object.fromEntries([...students,...archiveStudents].map(s=>[s.id,s])),[students,archiveStudents])
 const rows=items.map(x=>({...x,student:sm[x.student_id]})).filter(x=>x.student).filter(x=>(x.student.first_name+' '+x.student.last_name).toLocaleLowerCase('tr').includes(q.toLocaleLowerCase('tr')))
 const canUpdate=profile?.role==='super_admin'||permissions?.can_update
 async function reactivate(){if(!restore?.student||!restore.class_id)return setMsg('Aktif sınıfı seçiniz.');const {error}=await supabase.rpc('reactivate_student',{p_student:restore.student.id,p_class:restore.class_id});if(error)return setMsg(error.message);setMsg('Öğrenci yeniden aktif duruma alındı.');setRestore(null);const {data:i}=await supabase.from('student_departures').select('*').order('departure_date',{ascending:false});setItems(i||[]);const {data:s}=await supabase.from('students').select('*').in('student_status',['graduated','departed']);setArchiveStudents(s||[]);onRefresh&&await onRefresh()}
 const reason=k=>({parent_request:'Veli Talebi',transfer:'Nakil',discipline:'Disiplin',health:'Sağlık',own_request:'Kendi İsteği',other:'Diğer'}[k]||k||'—')
 return <section className="graduatesPro"><div className="gradHero departureHero"><div><small>E-GÖLKENT · ÖĞRENCİ YAŞAM DÖNGÜSÜ</small><h2>Ayrılan Öğrenciler Arşivi</h2><p>Programını tamamlamadan kurumdan ayrılan öğrencilerin kurumsal kayıt ve takip alanı.</p></div></div><div className="gradStats"><div><span>Toplam Ayrılan</span><b>{items.length}</b></div><div><span>Bu Yıl</span><b>{items.filter(x=>String(x.departure_date||'').startsWith(String(new Date().getFullYear()))).length}</b></div><div><span>Nakil</span><b>{items.filter(x=>x.reason_category==='transfer').length}</b></div><div><span>Veli Talebi</span><b>{items.filter(x=>x.reason_category==='parent_request').length}</b></div></div><div className="gradTools"><input placeholder="Ayrılan öğrenci ara..." value={q} onChange={e=>setQ(e.target.value)}/></div><div className="tableWrap"><table><thead><tr><th>Öğrenci</th><th>Ayrılış Tarihi</th><th>Neden</th><th>Program</th><th>Gittiği Kurum</th><th>Açıklama</th><th>İşlem</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><b>{x.student.first_name} {x.student.last_name}</b></td><td>{x.departure_date||'—'}</td><td>{reason(x.reason_category)}</td><td>{x.last_program||'—'}</td><td>{x.destination_institution||'—'}</td><td>{x.reason_detail||'—'}</td><td>{canUpdate&&<button onClick={()=>setRestore({student:x.student,class_id:''})}>Aktife Geri Al</button>}</td></tr>)}{!rows.length&&<tr><td colSpan="7">Henüz ayrılan öğrenci kaydı bulunmuyor.</td></tr>}</tbody></table></div>{msg&&<div className="msg">{msg}</div>}{restore&&<div className="debtModalBackdrop"><div className="debtModal gradForm"><div className="debtModalHead"><div><small>ÖĞRENCİ YAŞAM DÖNGÜSÜ</small><h3>Aktife Geri Al</h3><p>{restore.student.first_name} {restore.student.last_name}</p></div><button onClick={()=>setRestore(null)}>✕</button></div><label>Aktif Sınıf<select value={restore.class_id} onChange={e=>setRestore({...restore,class_id:e.target.value})}><option value="">Sınıf seçiniz</option>{classes.map(x=><option key={x.id} value={x.id}>{x.code} — {x.name}</option>)}</select></label><div className="lifecycleWarn">Ayrılış kaydı ve eski geçmiş silinmez. Öğrenci aynı kimlikle yeniden aktif hale gelir.</div><button className="primary" onClick={reactivate}>Aktife Al</button></div></div>}</section>
}