'use client'
import {useEffect,useMemo,useState} from 'react'
import ArchiveBars from './ArchiveBars'

const emptyLegacy={first:'',last:'',birth:'',phone:'',date:'',program:'',reason:'other',detail:'',destination:''}
const reasonLabel=k=>({parent_request:'Veli Talebi',transfer:'Nakil',discipline:'Disiplin',health:'Sağlık',own_request:'Kendi İsteği',other:'Diğer'}[k]||k||'—')

export default function DepartedStudentsModule({supabase,students=[],classes=[],profile,permissions,onRefresh}){
 const [items,setItems]=useState([]),[archiveStudents,setArchiveStudents]=useState([]),[q,setQ]=useState(''),[year,setYear]=useState(''),[reason,setReason]=useState(''),[program,setProgram]=useState('')
 const [restore,setRestore]=useState(null),[legacyOpen,setLegacyOpen]=useState(false),[importPreview,setImportPreview]=useState(null),[legacy,setLegacy]=useState(emptyLegacy),[msg,setMsg]=useState('')
 const canCreate=profile?.role==='super_admin'||permissions?.can_create
 const canUpdate=profile?.role==='super_admin'||permissions?.can_update
 const canExport=profile?.role==='super_admin'||permissions?.can_export
 const load=async()=>{const [{data:i},{data:s}]=await Promise.all([supabase.from('student_departures').select('*').order('departure_date',{ascending:false}),supabase.from('students').select('*').in('student_status',['graduated','departed'])]);setItems(i||[]);setArchiveStudents(s||[])}
 useEffect(()=>{load()},[])
 const sm=useMemo(()=>Object.fromEntries([...students,...archiveStudents].map(s=>[s.id,s])),[students,archiveStudents])
 const rows=useMemo(()=>items.map(x=>({...x,student:sm[x.student_id]})).filter(x=>x.student).filter(x=>(x.student.first_name+' '+x.student.last_name).toLocaleLowerCase('tr').includes(q.toLocaleLowerCase('tr'))).filter(x=>!year||String(x.departure_date||'').startsWith(year)).filter(x=>!reason||x.reason_category===reason).filter(x=>!program||(x.last_program||'')===program),[items,sm,q,year,reason,program])
 const years=useMemo(()=>[...new Set(items.map(x=>String(x.departure_date||'').slice(0,4)).filter(Boolean))].sort((a,b)=>b.localeCompare(a)),[items])
 const programs=useMemo(()=>[...new Set(items.map(x=>x.last_program).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'tr')),[items])
 async function readImport(file){if(!file)return;const XLSX=await import('xlsx');const buf=await file.arrayBuffer(),wb=XLSX.read(buf),ws=wb.Sheets[wb.SheetNames[0]],raw=XLSX.utils.sheet_to_json(ws,{defval:''});const val=v=>String(v??'').trim(),date=v=>{if(!v)return '';if(typeof v==='number'){const d=XLSX.SSF.parse_date_code(v);return d?String(d.y)+'-'+String(d.m).padStart(2,'0')+'-'+String(d.d).padStart(2,'0'):''}const s=val(v),m=s.match(/^(\d{1,2})[.\/-](\d{1,2})[.\/-](\d{4})$/);return m?m[3]+'-'+m[2].padStart(2,'0')+'-'+m[1].padStart(2,'0'):s};setImportPreview(raw.map((r,i)=>({row:i+2,first_name:val(r['Ad']||r['Adı']||r.first_name),last_name:val(r['Soyad']||r['Soyadı']||r.last_name),birth_date:date(r['Doğum Tarihi']||r.birth_date),personal_phone:val(r['Şahsi Telefon']||r['Telefon']||r.personal_phone),departure_date:date(r['Ayrılış Tarihi']||r.departure_date),program:val(r['Program']||r['Son Sınıf']||r.program),reason_category:val(r['Neden Kodu']||r.reason_category)||'other',reason_detail:val(r['Ayrılış Nedeni']||r['Açıklama']||r.reason_detail),destination:val(r['Gittiği Kurum']||r.destination)})))}
 async function commitImport(){const valid=(importPreview||[]).filter(x=>x.first_name&&x.last_name).map(({row,...x})=>x);if(!valid.length)return setMsg('Aktarılabilir kayıt bulunamadı.');const {data,error}=await supabase.rpc('import_legacy_departures',{p_rows:valid});if(error)return setMsg(error.message);setMsg('Toplu aktarım tamamlandı: '+(data?.inserted||0)+' eklendi, '+(data?.skipped_duplicates||0)+' mükerrer atlandı, '+(data?.errors?.length||0)+' hata.');setImportPreview(null);await load()}
 async function addLegacy(e){e.preventDefault();setMsg('');const {error}=await supabase.rpc('add_legacy_departed',{p_first:legacy.first,p_last:legacy.last,p_birth:legacy.birth||null,p_phone:legacy.phone||null,p_departure:legacy.date||null,p_program:legacy.program||null,p_reason:legacy.reason,p_detail:legacy.detail||null,p_destination:legacy.destination||null});if(error)return setMsg(error.message);setLegacy(emptyLegacy);setLegacyOpen(false);setMsg('Geçmiş ayrılan öğrenci arşive eklendi.');await load()}
 async function reactivate(){if(!restore?.student||!restore.class_id)return setMsg('Aktif sınıfı seçiniz.');const {error}=await supabase.rpc('reactivate_student',{p_student:restore.student.id,p_class:restore.class_id});if(error)return setMsg(error.message);setRestore(null);setMsg('Öğrenci yeniden aktif duruma alındı.');await load();if(onRefresh)await onRefresh()}
 function excel(){if(!canExport)return;import('xlsx').then(XLSX=>{const data=rows.map((x,i)=>({'Sıra':i+1,'Ad Soyad':x.student.first_name+' '+x.student.last_name,'Şahsi Telefon':x.student.personal_phone||'','Ayrılış Tarihi':x.departure_date||'','Neden':reasonLabel(x.reason_category),'Program / Son Sınıf':x.last_program||'','Gittiği Kurum':x.destination_institution||'','Açıklama':x.reason_detail||''}));const ws=XLSX.utils.json_to_sheet(data,{origin:'A5'});XLSX.utils.sheet_add_aoa(ws,[['E-GÖLKENT'],['Gölkent Erkek Yatılı Hafızlık Kur’an Kursu'],['Ayrılan Öğrenciler Kurumsal Arşiv Raporu'],['Rapor Tarihi',new Date().toLocaleDateString('tr-TR')]],{origin:'A1'});ws['!cols']=[{wch:7},{wch:30},{wch:18},{wch:18},{wch:18},{wch:22},{wch:28},{wch:40}];const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Ayrılan Öğrenciler');XLSX.writeFile(wb,'E-GOLKENT-Ayrilan-Ogrenciler-Arsivi.xlsx')})}
 function printReport(){if(!canExport)return;const body=rows.map((x,i)=>`<tr><td>${i+1}</td><td>${x.student.first_name} ${x.student.last_name}</td><td>${x.departure_date||'—'}</td><td>${reasonLabel(x.reason_category)}</td><td>${x.last_program||'—'}</td><td>${x.destination_institution||'—'}</td></tr>`).join('');const w=window.open('','_blank');w.document.write(`<!doctype html><html lang="tr"><head><meta charset="utf-8"><title>Ayrılan Öğrenciler Arşivi</title><style>body{font-family:Arial,sans-serif;padding:32px;color:#173f4d}h1{margin-bottom:2px}small{color:#667}table{width:100%;border-collapse:collapse;margin-top:22px;font-size:12px}th,td{border:1px solid #bbb;padding:7px;text-align:left}th{background:#eee}@media print{button{display:none}}</style></head><body><h1>E-GÖLKENT</h1><b>Gölkent Erkek Yatılı Hafızlık Kur’an Kursu</b><h2>Ayrılan Öğrenciler Kurumsal Arşiv Raporu</h2><small>Rapor Tarihi: ${new Date().toLocaleDateString('tr-TR')} · Toplam: ${rows.length}</small><table><thead><tr><th>#</th><th>Öğrenci</th><th>Ayrılış</th><th>Neden</th><th>Program</th><th>Gittiği Kurum</th></tr></thead><tbody>${body}</tbody></table><script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close()}
 const yearStats=useMemo(()=>Object.entries(items.reduce((a,x)=>{const y=(x.departure_date||'').slice(0,4)||'Tarih Yok';a[y]=(a[y]||0)+1;return a},{})).sort((a,b)=>String(b[0]).localeCompare(String(a[0]))).slice(0,8),[items])
 const reasonStats=useMemo(()=>Object.entries(items.reduce((a,x)=>{const r=reasonLabel(x.reason_category);a[r]=(a[r]||0)+1;return a},{})).sort((a,b)=>b[1]-a[1]),[items])
 const programStats=useMemo(()=>Object.entries(items.reduce((a,x)=>{const p=x.last_program||'Belirtilmemiş';a[p]=(a[p]||0)+1;return a},{})).sort((a,b)=>b[1]-a[1]).slice(0,8),[items])
 const now=new Date().getFullYear()
 return <section className="graduatesPro">
  <div className="gradHero departureHero"><div><small>E-GÖLKENT · ÖĞRENCİ YAŞAM DÖNGÜSÜ</small><h2>Ayrılan Öğrenciler Arşivi</h2><p>Programını tamamlamadan kurumdan ayrılan öğrencilerin kurumsal kayıt ve takip alanı.</p></div></div>
  <div className="gradStats"><div><span>Toplam Ayrılan</span><b>{items.length}</b></div><div><span>Bu Yıl</span><b>{items.filter(x=>String(x.departure_date||'').startsWith(String(now))).length}</b></div><div><span>Nakil</span><b>{items.filter(x=>x.reason_category==='transfer').length}</b></div><div><span>Veli Talebi</span><b>{items.filter(x=>x.reason_category==='parent_request').length}</b></div></div><div className="archiveCharts"><ArchiveBars title="Yıllara Göre Ayrılış" data={yearStats}/><ArchiveBars title="Ayrılış Nedenleri" data={reasonStats}/><ArchiveBars title="Program / Son Sınıf Dağılımı" data={programStats}/></div>
  <div className="gradTools"><input placeholder="Ayrılan öğrenci ara..." value={q} onChange={e=>setQ(e.target.value)}/><select value={year} onChange={e=>setYear(e.target.value)}><option value="">Tüm yıllar</option>{years.map(y=><option key={y}>{y}</option>)}</select><select value={reason} onChange={e=>setReason(e.target.value)}><option value="">Tüm nedenler</option><option value="own_request">Kendi İsteği</option><option value="parent_request">Veli Talebi</option><option value="transfer">Nakil</option><option value="discipline">Disiplin</option><option value="health">Sağlık</option><option value="other">Diğer</option></select><select value={program} onChange={e=>setProgram(e.target.value)}><option value="">Tüm programlar</option>{programs.map(p=><option key={p}>{p}</option>)}</select>{canCreate&&<button onClick={()=>setLegacyOpen(true)}>+ Geçmiş Ayrılan Ekle</button>}{canCreate&&<label className="importBtn">Excel’den Aktar<input hidden type="file" accept=".xlsx,.xls" onChange={e=>readImport(e.target.files?.[0])}/></label>}{canExport&&<button onClick={excel}>Excel Raporu</button>}{canExport&&<button onClick={printReport}>PDF / Yazdır</button>}</div>
  <div className="tableWrap"><table><thead><tr><th>Öğrenci</th><th>Ayrılış Tarihi</th><th>Neden</th><th>Program</th><th>Gittiği Kurum</th><th>Açıklama</th><th>İşlem</th></tr></thead><tbody>
   {rows.map(x=><tr key={x.id}><td><b>{x.student.first_name} {x.student.last_name}</b></td><td>{x.departure_date||'—'}</td><td>{reasonLabel(x.reason_category)}</td><td>{x.last_program||'—'}</td><td>{x.destination_institution||'—'}</td><td>{x.reason_detail||'—'}</td><td>{canUpdate&&<button onClick={()=>setRestore({student:x.student,class_id:''})}>Aktife Geri Al</button>}</td></tr>)}
   {!rows.length&&<tr><td colSpan="7">Henüz ayrılan öğrenci kaydı bulunmuyor.</td></tr>}
  </tbody></table></div>
  {msg&&<div className="msg">{msg}</div>}{importPreview&&<ImportPreview rows={importPreview} onClose={()=>setImportPreview(null)} onImport={commitImport}/>}
  {legacyOpen&&<LegacyDepartureForm legacy={legacy} setLegacy={setLegacy} onClose={()=>setLegacyOpen(false)} onSubmit={addLegacy}/>}
  {restore&&<RestoreModal restore={restore} setRestore={setRestore} classes={classes} onSubmit={reactivate}/>}
 </section>
}

function LegacyDepartureForm({legacy,setLegacy,onClose,onSubmit}){
 return <div className="debtModalBackdrop"><form className="debtModal gradForm" onSubmit={onSubmit}>
  <div className="debtModalHead"><div><small>ARŞİV KAYDI</small><h3>Geçmiş Ayrılan Öğrenci Ekle</h3><p>E-Gölkent öncesi ayrılan öğrenciler için.</p></div><button type="button" onClick={onClose}>✕</button></div>
  <div className="gradFormGrid">
   <input required placeholder="Adı" value={legacy.first} onChange={e=>setLegacy({...legacy,first:e.target.value})}/>
   <input required placeholder="Soyadı" value={legacy.last} onChange={e=>setLegacy({...legacy,last:e.target.value})}/>
   <label>Doğum Tarihi<input type="date" value={legacy.birth} onChange={e=>setLegacy({...legacy,birth:e.target.value})}/></label>
   <input placeholder="Şahsi telefon" value={legacy.phone} onChange={e=>setLegacy({...legacy,phone:e.target.value})}/>
   <label>Ayrılış Tarihi<input type="date" value={legacy.date} onChange={e=>setLegacy({...legacy,date:e.target.value})}/></label>
   <input placeholder="Program / Son Sınıf" value={legacy.program} onChange={e=>setLegacy({...legacy,program:e.target.value})}/>
   <label>Ayrılış Nedeni<select value={legacy.reason} onChange={e=>setLegacy({...legacy,reason:e.target.value})}><option value="parent_request">Veli Talebi</option><option value="transfer">Nakil</option><option value="discipline">Disiplin</option><option value="health">Sağlık</option><option value="own_request">Kendi İsteği</option><option value="other">Diğer</option></select></label>
   <input placeholder="Gittiği kurum" value={legacy.destination} onChange={e=>setLegacy({...legacy,destination:e.target.value})}/>
   <textarea placeholder="Ayrılış açıklaması" value={legacy.detail} onChange={e=>setLegacy({...legacy,detail:e.target.value})}/>
  </div>
  <div className="lifecycleWarn">Muhtemel mükerrer kayıtlar sunucu tarafında kontrol edilir. Bu kayıt aktif öğrenci listesine eklenmez.</div>
  <button className="primary">Arşive Kaydet</button>
 </form></div>
}
function RestoreModal({restore,setRestore,classes,onSubmit}){
 return <div className="debtModalBackdrop"><div className="debtModal gradForm">
  <div className="debtModalHead"><div><small>ÖĞRENCİ YAŞAM DÖNGÜSÜ</small><h3>Aktife Geri Al</h3><p>{restore.student.first_name} {restore.student.last_name}</p></div><button onClick={()=>setRestore(null)}>✕</button></div>
  <label>Aktif Sınıf<select value={restore.class_id} onChange={e=>setRestore({...restore,class_id:e.target.value})}><option value="">Sınıf seçiniz</option>{classes.map(x=><option key={x.id} value={x.id}>{x.code} — {x.name}</option>)}</select></label>
  <div className="lifecycleWarn">Ayrılış kaydı ve eski geçmiş silinmez. Öğrenci aynı kimlikle yeniden aktif hale gelir.</div>
  <button className="primary" onClick={onSubmit}>Aktife Al</button>
 </div></div>
}

function ImportPreview({rows,onClose,onImport}){const valid=rows.filter(x=>x.first_name&&x.last_name).length;return <div className="debtModalBackdrop"><div className="debtModal graduateDossier"><div className="debtModalHead"><div><small>TOPLU ARŞİV AKTARIMI</small><h3>Ayrılan Öğrenciler · Excel Önizleme</h3><p>{rows.length} satır · {valid} aktarılabilir · {rows.length-valid} eksik</p></div><button onClick={onClose}>✕</button></div><div className="tableWrap"><table><thead><tr><th>Satır</th><th>Ad Soyad</th><th>Ayrılış</th><th>Program</th><th>Neden</th><th>Durum</th></tr></thead><tbody>{rows.slice(0,100).map(x=><tr key={x.row}><td>{x.row}</td><td>{x.first_name} {x.last_name}</td><td>{x.departure_date||'—'}</td><td>{x.program||'—'}</td><td>{x.reason_detail||x.reason_category||'—'}</td><td>{x.first_name&&x.last_name?'Hazır':'Eksik ad/soyad'}</td></tr>)}</tbody></table></div><div className="lifecycleWarn">Mükerrer kayıtlar veritabanında tekrar kontrol edilir ve atlanır.</div><button className="primary" onClick={onImport}>Geçerli Kayıtları Aktar</button></div></div>}
