'use client'
import useLiveRefresh from '../hooks/useLiveRefresh'
import {useEffect,useMemo,useState} from 'react'
export default function EducationDashboard({supabase,students,classes,institution}){
 const [date,setDate]=useState(new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Istanbul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())),[lessons,setLessons]=useState([]),[attendance,setAttendance]=useState([]),[hafRows,setHafRows]=useState([]),[yuzRows,setYuzRows]=useState([]),[kapRows,setKapRows]=useState([]),[hoverCard,setHoverCard]=useState(''),[exporting,setExporting]=useState(false),[exportError,setExportError]=useState('')
 async function load(){const [{data:l},{data:a},{data:h},{data:y},{data:k}]=await Promise.all([supabase.from('lesson_records').select('student_id,program,quality,status_code,work_value').eq('lesson_date',date),supabase.from('attendance').select('student_id,status').eq('attendance_date',date),supabase.from('hafizlik_daily_records').select('student_id,quality,status_code,work_value').eq('lesson_date',date),supabase.from('yuzune_progress').select('student_id,result,quality,lesson_date').eq('lesson_date',date),supabase.from('kap_daily_records').select('student_id,juz_values,juz_no,quality,status_code').eq('lesson_date',date)]);setLessons(l||[]);setAttendance(a||[]);setHafRows(h||[]);setYuzRows(y||[]);setKapRows(k||[])}
 useEffect(()=>{load()},[date])
 useLiveRefresh(supabase,['lesson_records','attendance','hafizlik_daily_records','yuzune_progress','kap_daily_records'],load)
 const active=students.filter(s=>(s.student_status||s.status)==='active'),programOf=s=>classes.find(c=>c.id===s.class_id)?.program
 const grouped=useMemo(()=>{const programs=[['hafizlik','Hafızlık'],['yuzune','Yüzüne'],['kap','Kur’an Anlama']];const hasValue=v=>String(v??'').trim().length>0;const hafGiven=new Set(hafRows.filter(r=>!r.status_code&&(hasValue(r.work_value)||!!r.quality)).map(r=>r.student_id));const yuzGiven=new Set(yuzRows.filter(r=>r.result==='plus').map(r=>r.student_id));const kapGiven=new Set(kapRows.filter(r=>!r.status_code&&((Array.isArray(r.juz_values)&&r.juz_values.length>0)||r.juz_no!=null)).map(r=>r.student_id));const legacyByProgram={hafizlik:new Set(),yuzune:new Set(),kap:new Set()};lessons.forEach(r=>{if(!r.status_code&&(hasValue(r.work_value)||!!r.quality)&&legacyByProgram[r.program])legacyByProgram[r.program].add(r.student_id)});return programs.map(([key,label])=>{const roster=active.filter(st=>programOf(st)===key);const primary=key==='hafizlik'?hafGiven:key==='yuzune'?yuzGiven:kapGiven;const given=roster.filter(st=>primary.has(st.id)||legacyByProgram[key].has(st.id));const notGiven=roster.filter(st=>!primary.has(st.id)&&!legacyByProgram[key].has(st.id));return {key,label,roster,given,notGiven}})},[active,classes,hafRows,yuzRows,kapRows,lessons])
 const counts=useMemo(()=>{const hs=code=>new Set(hafRows.filter(x=>x.status_code===code).map(x=>x.student_id)).size,st=x=>attendance.filter(a=>a.status===x).length;return{given:grouped.reduce((n,g)=>n+g.given.length,0),notGiven:grouped.reduce((n,g)=>n+g.notGiven.length,0),absent:Math.max(st('absent'),hs('G')),sick:Math.max(st('sick'),hs('H')),excused:Math.max(st('excused'),hs('İ')+hs('M')),late:st('late'),x:hs('X'),boarding:active.filter(x=>x.residency==='boarding').length,haf:grouped[0]?.roster.length||0,yuz:grouped[1]?.roster.length||0,kap:grouped[2]?.roster.length||0}},[grouped,attendance,hafRows,active])
 const classCode=st=>{const c=classes.find(c=>c.id===st.class_id);return String(c?.code||c?.name||'').trim()}
 const sortedStudents=people=>[...people].sort((a,b)=>{const byClass=classCode(a).localeCompare(classCode(b),'tr',{numeric:true,sensitivity:'base'});return byClass||String(a.first_name||'').localeCompare(String(b.first_name||''),'tr',{sensitivity:'base'})||String(a.last_name||'').localeCompare(String(b.last_name||''),'tr',{sensitivity:'base'})})
 const studentLabel=st=>(st.first_name||'')+' '+(st.last_name||'')+' · '+(classCode(st)||'Sınıf belirtilmemiş')

 async function downloadDailyPdf(){
  setExporting(true);setExportError('');
  try{
   const [{default:pdfMake},fonts]=await Promise.all([import('pdfmake/build/pdfmake'),import('pdfmake/build/vfs_fonts')]);
   const vfs=fonts?.default?.pdfMake?.vfs||fonts?.default?.vfs||fonts?.pdfMake?.vfs||fonts?.vfs||fonts?.default||fonts;
   if(!vfs||!vfs['Roboto-Regular.ttf'])throw new Error('PDF yazı tipi yüklenemedi');
   pdfMake.vfs=vfs;
   const readableDate=date.split('-').reverse().join('.');
   const navy='#17384b',teal='#137d83',muted='#647986';
   const content=[
    {text:String(institution?.name||'GÖLKENT ERKEK YATILI HAFIZLIK KUR’AN KURSU').toLocaleUpperCase('tr-TR'),style:'institution'},
    {text:'GÜNLÜK DERS KATILIM RAPORU',style:'reportTitle'},
    {columns:[{text:'Rapor Tarihi: '+readableDate,style:'meta'},{text:'E-GÖLKENT · Eğitim Yönetim Sistemi',style:'meta',alignment:'right'}],margin:[0,0,0,18]},
    {table:{widths:['*','*','*','*'],body:[[{text:'PROGRAM',style:'tableHeader'},{text:'TOPLAM',style:'tableHeader'},{text:'DERS VEREN',style:'tableHeader'},{text:'DERS VERMEYEN',style:'tableHeader'}],...grouped.map(g=>[{text:g.label,style:'tableBody'},{text:String(g.roster.length),style:'tableBody'},{text:String(g.given.length),style:'tableBody'},{text:String(g.notGiven.length),style:'tableBody'}])]},layout:'lightHorizontalLines',margin:[0,0,0,16]}
   ];
   for(const g of grouped){
    content.push({text:g.label.toLocaleUpperCase('tr-TR'),style:'section',margin:[0,12,0,7],keepWithNext:true});
    for(const [title,people] of [['Ders Veren',g.given],['Ders Vermeyen',g.notGiven]]){
     content.push({text:title+' · '+people.length+' öğrenci',style:'subsection',keepWithNext:true,margin:[0,8,0,5]});
     const sorted=sortedStudents(people);
     if(!sorted.length){content.push({text:'Kayıt bulunmuyor.',style:'empty'});continue}
     const body=[[{text:'SIRA',style:'tableHeader'},{text:'SINIF',style:'tableHeader'},{text:'ÖĞRENCİ ADI SOYADI',style:'tableHeader'}],...sorted.map((st,i)=>[{text:String(i+1),style:'tableBody'},{text:classCode(st)||'—',style:'tableBody'},{text:((st.first_name||'')+' '+(st.last_name||'')).trim(),style:'tableBody'}])];
     content.push({table:{headerRows:1,dontBreakRows:true,widths:[38,65,'*'],body},layout:{fillColor:(i)=>i===0?navy:i%2===0?'#f1f6f8':null,hLineColor:()=> '#d6e2e6',vLineColor:()=> '#d6e2e6',hLineWidth:()=>0.5,vLineWidth:()=>0.5},margin:[0,0,0,9]})
    }
   }
   const doc={pageSize:'A4',pageMargins:[40,45,40,48],content,defaultStyle:{font:'Roboto',fontSize:9,color:navy},styles:{institution:{fontSize:11,bold:true,color:teal,margin:[0,0,0,10]},reportTitle:{fontSize:19,bold:true,color:navy,margin:[0,0,0,12]},meta:{fontSize:9,color:muted},section:{fontSize:13,bold:true,color:teal},subsection:{fontSize:10,bold:true,color:navy},tableHeader:{fontSize:8,bold:true,color:'#ffffff',margin:[3,5,3,5]},tableBody:{fontSize:9,margin:[3,4,3,4]},empty:{fontSize:9,italics:true,color:muted}},footer:(page,total)=>({columns:[{text:'E-GÖLKENT · Günlük Eğitim Raporu',color:muted},{text:'Sayfa '+page+' / '+total,alignment:'right',color:muted}],margin:[40,12,40,0],fontSize:8})};
   pdfMake.createPdf(doc).download('E-GOLKENT-Gunluk-Ders-Raporu-'+date+'.pdf');
  }catch(error){setExportError('PDF oluşturulamadı: '+(error?.message||'Bilinmeyen hata'))}
  finally{setExporting(false)}
 }
 const qualityLabels={saglam:'Sağlam',iyi:'İyi',orta:'Orta',zayif:'Zayıf'};
 const qualityColors={saglam:'#1c9b65',iyi:'#397fda',orta:'#e8b548',zayif:'#d95757'};
 const [qualitySelection,setQualitySelection]=useState({});
 const qualityChart=(program,items)=>{const total=items.reduce((sum,item)=>sum+item[1],0);let cumulative=0;const arcs=items.map(([key,count])=>{const start=cumulative;const length=total?count/total*100:0;cumulative+=length;return {key,count,start,length}});const activeKey=qualitySelection[program]||null;const selected=items.find(([key])=>key===activeKey);return <div className="eduDonutLayout"><div className="eduDonutChart" style={{background:total?'conic-gradient('+arcs.filter(a=>a.length>0).map(a=>qualityColors[a.key]+' '+a.start+'% '+(a.start+a.length)+'%').join(',')+')':'#e7edf0'}} role="group" aria-label={program+' kalite dağılımı'}><div className="eduDonutCenter"><b>{selected?selected[1]:total}</b><span>{selected?qualityLabels[selected[0]]:'Değerlendirme'}</span><strong>{selected?(total?Math.round(selected[1]/total*100):0)+'%':'Toplam'}</strong></div></div><div className="eduDonutLegend">{items.map(([key,count])=><button type="button" key={key} className={'eduDonutLegendItem '+(activeKey===key?'selected':'')} onMouseEnter={()=>setQualitySelection(p=>({...p,[program]:key}))} onMouseLeave={()=>setQualitySelection(p=>({...p,[program]:null}))} onFocus={()=>setQualitySelection(p=>({...p,[program]:key}))} onClick={()=>setQualitySelection(p=>({...p,[program]:p[program]===key?null:key}))} aria-label={qualityLabels[key]+': '+count+' değerlendirme, '+(total?Math.round(count/total*100):0)+' yüzde'}><i style={{background:qualityColors[key]}}/><span>{qualityLabels[key]}</span><b>{count}</b><small>{total?Math.round(count/total*100):0}%</small></button>)}</div></div>};
 const qualityKeys=['saglam','iyi','orta','zayif'];const hafQualities=qualityKeys.map(k=>[k,hafRows.filter(x=>x.quality===k).length]),hafQt=hafQualities.reduce((a,x)=>a+x[1],0)||1;const yuzQualities=qualityKeys.map(k=>[k,yuzRows.filter(x=>x.result==='plus'&&x.quality===k).length]),yuzQt=yuzQualities.reduce((a,x)=>a+x[1],0)||1
 const pace={};active.filter(x=>programOf(x)==='hafizlik').forEach(x=>{const n=String(x.hafizlik_pace||'').match(/\d+/)?.[0];if(n)pace[n]=(pace[n]||0)+1});const max=Math.max(1,...Object.values(pace))
 const cap=institution?.student_capacity||0,bed=institution?.bed_capacity||0
 return <div className="eduDash"><div className="eduDashHead"><div><small>E-GÖLKENT · CANLI EĞİTİM ANALİZİ</small><h2>Günlük Eğitim Gösterge Paneli</h2></div><div className="eduDashActions"><input type="date" value={date} onChange={e=>setDate(e.target.value)}/><button type="button" className="eduPdfButton" disabled={exporting} onClick={downloadDailyPdf}>{exporting?"PDF hazırlanıyor…":"Günlük Ders Raporu · PDF İndir"}</button></div></div>
 {exportError&&<p role="alert" className="eduExportError">{exportError}</p>}<div className="eduProgramGrid">{grouped.map(g=><section key={g.key} className="eduProgramCard"><h3>{g.label}</h3><p>Toplam {g.roster.length} öğrenci</p><div className="eduProgramNumbers">{[['given','Ders Veren',g.given],['missing','Ders Vermeyen',g.notGiven]].map(([kind,label,people])=><div key={kind} className={'eduProgramNumber '+kind} onMouseEnter={()=>{if(window.matchMedia('(hover:hover)').matches)setHoverCard(g.key+'-'+kind)}} onMouseLeave={()=>{if(window.matchMedia('(hover:hover)').matches)setHoverCard('')}} onClick={()=>setHoverCard(current=>current===g.key+'-'+kind?'':g.key+'-'+kind)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setHoverCard(current=>current===g.key+'-'+kind?'':g.key+'-'+kind)}if(e.key==='Escape')setHoverCard('')}} tabIndex={0} role="button" aria-expanded={hoverCard===g.key+'-'+kind} aria-label={g.label+' '+label+': '+people.length+' öğrenci. İsimler için üzerine gelin.'}><span>{label}</span><b>{people.length}</b>{hoverCard===g.key+'-'+kind&&<div className="eduProgramPopover"><strong>{g.label} · {label} ({people.length})</strong>{people.length?<ul>{sortedStudents(people).map(st=><li key={st.id}>{studentLabel(st)}</li>)}</ul>:<p>Bu grupta öğrenci bulunmuyor.</p>}</div>}</div>)}</div></section>)}</div>
 <div className="eduStatGrid">{[['Aktif Öğrenci',active.length],['Hafızlık',counts.haf],['Yüzüne',counts.yuz],['KAP',counts.kap],['Yatılı',counts.boarding],['Ders Veren',counts.given],['Ders Vermeyen',counts.notGiven],['Hasta',counts.sick],['İzinli / Mazeretli',counts.excused],['Gelmeyen',counts.absent]].map(([x,n])=><div className="eduStat" key={x}><span>{x}</span><b>{n}</b></div>)}</div>
 <div className="eduGrid"><section className="panel"><h3>Kapasite Durumu</h3><div className="capacityRow"><span>Öğrenci Kapasitesi <b>{active.length}{cap?' / '+cap:''}</b></span><div><i style={{width:(cap?Math.min(100,active.length/cap*100):0)+'%'}}/></div><strong>{cap?Math.round(active.length/cap*100)+'%':'Kapasite girilmedi'}</strong></div><div className="capacityRow"><span>Yatak Kapasitesi <b>{counts.boarding}{bed?' / '+bed:''}</b></span><div><i style={{width:(bed?Math.min(100,counts.boarding/bed*100):0)+'%'}}/></div><strong>{bed?Math.round(counts.boarding/bed*100)+'%':'Kapasite girilmedi'}</strong></div></section>
 <section className="panel"><h3>Hafızlık · Ezber Kalitesi</h3><p className="eduQualitySub">Hafızlık Ders Cetveli günlük kayıtları</p>{qualityChart('Hafızlık',hafQualities)}</section></div><div className="eduGrid"><section className="panel"><h3>Yüzüne · Ders Kalitesi</h3><p className="eduQualitySub">Yüzüne Cetveli günlük ders kayıtları</p>{qualityChart('Yüzüne',yuzQualities)}</section></div>
 <section className="panel"><div className="panelHead"><div><h3>Hafızlık Süreçleri</h3><p>Öğrencilerin “kaçla gidiyor” değerine göre canlı dağılımı.</p></div></div><div className="paceChart">{Array.from({length:20},(_,i)=>i+1).map(n=><div key={n} title={n+' ile giden '+(pace[n]||0)+' öğrenci'}><b>{pace[n]||0}</b><i style={{height:Math.max(3,(pace[n]||0)/max*120)+'px'}}/><span>{n}</span></div>)}</div></section></div>
}