'use client'
import {useEffect,useMemo,useState} from 'react'
export default function EducationDashboard({supabase,students,classes,institution}){
 const [date,setDate]=useState(new Date().toISOString().slice(0,10)),[lessons,setLessons]=useState([]),[attendance,setAttendance]=useState([]),[hafRows,setHafRows]=useState([]),[yuzRows,setYuzRows]=useState([])
 useEffect(()=>{(async()=>{const [{data:l},{data:a},{data:h},{data:y}]=await Promise.all([supabase.from('lesson_records').select('student_id,program,quality,status_code,work_value').eq('lesson_date',date),supabase.from('attendance').select('student_id,status').eq('attendance_date',date),supabase.from('hafizlik_daily_records').select('student_id,quality,status_code,work_value').eq('lesson_date',date),supabase.from('yuzune_progress').select('student_id,result,quality,lesson_date').eq('lesson_date',date)]);setLessons(l||[]);setAttendance(a||[]);setHafRows(h||[]);setYuzRows(y||[])})()},[date])
 const active=students.filter(s=>s.status==='active'),programOf=s=>classes.find(c=>c.id===s.class_id)?.program
 const counts=useMemo(()=>{const hafGiven=new Set(hafRows.filter(x=>x.quality||x.work_value).map(x=>x.student_id)),yuzGiven=new Set(yuzRows.filter(x=>x.result==='plus').map(x=>x.student_id)),legacy=new Set(lessons.map(x=>x.student_id)),unique=new Set([...hafGiven,...yuzGiven,...legacy]);const hs=code=>new Set(hafRows.filter(x=>x.status_code===code).map(x=>x.student_id)).size,st=x=>attendance.filter(a=>a.status===x).length;return{given:unique.size,notGiven:Math.max(0,active.length-unique.size),absent:Math.max(st('absent'),hs('G')),sick:Math.max(st('sick'),hs('H')),excused:Math.max(st('excused'),hs('İ')+hs('M')),late:st('late'),x:hs('X'),boarding:active.filter(x=>x.residency==='boarding').length,haf:active.filter(x=>programOf(x)==='hafizlik').length,yuz:active.filter(x=>programOf(x)==='yuzune').length,kap:active.filter(x=>programOf(x)==='kap').length}},[lessons,attendance,hafRows,yuzRows,students,classes])
 const qualityKeys=['saglam','iyi','orta','zayif'];const hafQualities=qualityKeys.map(k=>[k,hafRows.filter(x=>x.quality===k).length]),hafQt=hafQualities.reduce((a,x)=>a+x[1],0)||1;const yuzQualities=qualityKeys.map(k=>[k,yuzRows.filter(x=>x.result==='plus'&&x.quality===k).length]),yuzQt=yuzQualities.reduce((a,x)=>a+x[1],0)||1
 const pace={};active.filter(x=>programOf(x)==='hafizlik').forEach(x=>{const n=String(x.hafizlik_pace||'').match(/\d+/)?.[0];if(n)pace[n]=(pace[n]||0)+1});const max=Math.max(1,...Object.values(pace))
 const cap=institution?.student_capacity||0,bed=institution?.bed_capacity||0
 return <div className="eduDash"><div className="eduDashHead"><div><small>E-GÖLKENT · CANLI EĞİTİM ANALİZİ</small><h2>Günlük Eğitim Gösterge Paneli</h2></div><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></div>
 <div className="eduStatGrid">{[['Toplam Öğrenci',active.length],['Hafızlık',counts.haf],['Yüzüne',counts.yuz],['KAP',counts.kap],['Yatılı',counts.boarding],['Ders Veren',counts.given],['Ders Vermeyen',Math.max(counts.notGiven,counts.x)],['Hasta',counts.sick],['İzinli / Mazeretli',counts.excused],['Gelmeyen',counts.absent]].map(([x,n])=><div className="eduStat" key={x}><span>{x}</span><b>{n}</b></div>)}</div>
 <div className="eduGrid"><section className="panel"><h3>Kapasite Durumu</h3><div className="capacityRow"><span>Öğrenci Kapasitesi <b>{active.length}{cap?' / '+cap:''}</b></span><div><i style={{width:(cap?Math.min(100,active.length/cap*100):0)+'%'}}/></div><strong>{cap?Math.round(active.length/cap*100)+'%':'Kapasite girilmedi'}</strong></div><div className="capacityRow"><span>Yatak Kapasitesi <b>{counts.boarding}{bed?' / '+bed:''}</b></span><div><i style={{width:(bed?Math.min(100,counts.boarding/bed*100):0)+'%'}}/></div><strong>{bed?Math.round(counts.boarding/bed*100)+'%':'Kapasite girilmedi'}</strong></div></section>
 <section className="panel"><h3>Hafızlık · Ezber Kalitesi</h3><p className="eduQualitySub">Hafızlık Ders Cetveli günlük kayıtları</p><div className="qualityBars">{hafQualities.map(([k,n])=><div key={k}><span>{({saglam:'Sağlam',iyi:'İyi',orta:'Orta',zayif:'Zayıf'})[k]} <b>{n} · {Math.round(n/hafQt*100)}%</b></span><div><i className={'q-'+k} style={{width:(n/hafQt*100)+'%'}}/></div></div>)}</div></section></div><div className="eduGrid"><section className="panel"><h3>Yüzüne · Ders Kalitesi</h3><p className="eduQualitySub">Yüzüne Cetveli günlük ders kayıtları</p><div className="qualityBars">{yuzQualities.map(([k,n])=><div key={k}><span>{({saglam:'Sağlam',iyi:'İyi',orta:'Orta',zayif:'Zayıf'})[k]} <b>{n} · {Math.round(n/yuzQt*100)}%</b></span><div><i className={'q-'+k} style={{width:(n/yuzQt*100)+'%'}}/></div></div>)}</div></section></div>
 <section className="panel"><div className="panelHead"><div><h3>Hafızlık Süreçleri</h3><p>Öğrencilerin “kaçla gidiyor” değerine göre canlı dağılımı.</p></div></div><div className="paceChart">{Array.from({length:20},(_,i)=>i+1).map(n=><div key={n} title={n+' ile giden '+(pace[n]||0)+' öğrenci'}><b>{pace[n]||0}</b><i style={{height:Math.max(3,(pace[n]||0)/max*120)+'px'}}/><span>{n}</span></div>)}</div></section></div>
}