'use client'
import {useEffect,useMemo,useState} from 'react'
import * as XLSX from 'xlsx'
export default function GraduatesModule({supabase,students=[],profile,permissions}){
 const [items,setItems]=useState([]),[q,setQ]=useState(''),[year,setYear]=useState('')
 const admin=profile?.role==='super_admin',canExport=admin||permissions?.can_export
 const load=async()=>{const {data}=await supabase.from('student_graduations').select('*').order('graduation_date',{ascending:false});setItems(data||[])}
 useEffect(()=>{load()},[])
 const [archiveStudents,setArchiveStudents]=useState([]);useEffect(()=>{supabase.from('students').select('*').in('student_status',['graduated','departed']).then(({data})=>setArchiveStudents(data||[]))},[]);const sm=useMemo(()=>Object.fromEntries([...students,...archiveStudents].map(s=>[s.id,s])),[students,archiveStudents])
 const rows=useMemo(()=>items.map(g=>({...g,student:sm[g.student_id]})).filter(x=>x.student).filter(x=>{const n=(x.student.first_name+' '+x.student.last_name).toLocaleLowerCase('tr');return n.includes(q.toLocaleLowerCase('tr'))&&(!year||String(x.graduation_year||'')===year)}),[items,sm,q,year])
 const years=[...new Set(items.map(x=>x.graduation_year).filter(Boolean))].sort((a,b)=>b-a)
 const haf=items.filter(x=>x.program==='Hafızlık').length, yuz=items.filter(x=>x.program==='Yüzüne').length, now=new Date().getFullYear()
 function excel(){if(!canExport)return;const data=rows.map((x,i)=>({'Sıra':i+1,'Ad Soyad':x.student.first_name+' '+x.student.last_name,'Şahsi Telefon':x.student.personal_phone||'','Program':x.program||'','Mezuniyet Tarihi':x.graduation_date||'','Yüzüne Hocası':x.yuzune_teacher_name||'','Yüzüne Bitirme Tarihi':x.yuzune_completion_date||'','Hafızlık Hocası':x.hafizlik_teacher_name||'','Hafızlık Bitirme Tarihi':x.hafizlik_completion_date||'','Belge No':x.certificate_no||''}));const ws=XLSX.utils.json_to_sheet(data,{origin:'A5'});XLSX.utils.sheet_add_aoa(ws,[['E-GÖLKENT'],['Gölkent Erkek Yatılı Hafızlık Kur’an Kursu'],['Mezun Öğrenciler Kurumsal Arşiv Raporu'],['Rapor Tarihi',new Date().toLocaleDateString('tr-TR')]],{origin:'A1'});ws['!cols']=[{wch:7},{wch:30},{wch:18},{wch:16},{wch:18},{wch:25},{wch:20},{wch:25},{wch:20},{wch:18}];const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Mezunlar');XLSX.writeFile(wb,'E-GOLKENT-Mezun-Arsivi.xlsx')}
 return <section className="graduatesPro"><div className="gradHero"><div><small>E-GÖLKENT · KURUMSAL ARŞİV</small><h2>Mezuniyet ve Mezun Takip Sistemi</h2><p>Mezunların eğitim geçmişi ve kurumsal takibi tek merkezde.</p></div></div><div className="gradStats"><div><span>Toplam Mezun</span><b>{items.length}</b></div><div><span>Hafızlık</span><b>{haf}</b></div><div><span>Yüzüne</span><b>{yuz}</b></div><div><span>Bu Yıl</span><b>{items.filter(x=>x.graduation_year===now).length}</b></div></div><div className="gradTools"><input placeholder="Mezun ara..." value={q} onChange={e=>setQ(e.target.value)}/><select value={year} onChange={e=>setYear(e.target.value)}><option value="">Tüm yıllar</option>{years.map(y=><option key={y}>{y}</option>)}</select>{canExport&&<button onClick={excel}>Excel Raporu</button>}</div><div className="tableWrap"><table><thead><tr><th>Mezun</th><th>Program</th><th>Mezuniyet</th><th>Yüzüne Hocası</th><th>Hafızlık Hocası</th><th>Telefon</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><b>{x.student.first_name} {x.student.last_name}</b></td><td>{x.program||'—'}</td><td>{x.graduation_date||'—'}</td><td>{x.yuzune_teacher_name||'—'}</td><td>{x.hafizlik_teacher_name||'—'}</td><td>{x.student.personal_phone||'—'}</td></tr>)}{!rows.length&&<tr><td colSpan="6">Henüz mezun kaydı bulunmuyor.</td></tr>}</tbody></table></div></section>
}