'use client'
import {useEffect,useMemo,useState} from 'react'
export default function HafizlikMonthlyLedger({supabase,students,classInfo,session,month}){
 const list=students.filter(s=>s.class_id===classInfo?.id),[rows,setRows]=useState([]),[meta,setMeta]=useState({}),[msg,setMsg]=useState('')
 const days=useMemo(()=>{if(!month)return[];const [y,m]=month.split('-').map(Number),n=new Date(y,m,0).getDate();return Array.from({length:n},(_,i)=>String(i+1).padStart(2,'0'))},[month])
 async function load(){if(!classInfo?.id||!month)return;const {data,error}=await supabase.from('lesson_records').select('*').eq('class_id',classInfo.id).eq('program','hafizlik').gte('lesson_date',month+'-01').lte('lesson_date',month+'-31');if(error)return setMsg(error.message);setRows(data||[]);const m={};list.forEach(s=>m[s.id]={pace:s.hafizlik_pace||'',stage:s.hafizlik_current_stage||''});setMeta(m)}
 useEffect(()=>{load()},[classInfo?.id,month,students.length])
 const cell=(sid,d)=>rows.find(r=>r.student_id===sid&&r.lesson_date===month+'-'+d)
 async function saveMeta(st){const x=meta[st.id]||{};const {error}=await supabase.from('students').update({hafizlik_pace:x.pace||null,hafizlik_current_stage:x.stage||null}).eq('id',st.id);setMsg(error?error.message:st.first_name+' bilgileri kaydedildi.')}
 async function editCell(st,d){const old=cell(st.id,d),value=prompt(d+'. gün — Cüz (1-30 / 7-8) veya H, R, İ, T, X, M, G:',old?.status_code||old?.work_value||'');if(value===null)return;const v=value.trim().toUpperCase(),codes=['H','R','İ','I','T','X','M','G'];let quality=old?.quality||null,stage=old?.lesson_stage||meta[st.id]?.stage||null;if(!codes.includes(v)){const q=prompt('Kalite: sağlam / iyi / orta / zayıf',quality||'iyi');if(q!==null)quality={'sağlam':'saglam','saglam':'saglam','iyi':'iyi','orta':'orta','zayıf':'zayif','zayif':'zayif'}[q.toLowerCase()]||null}
 const payload={student_id:st.id,class_id:classInfo.id,teacher_id:session.user.id,lesson_date:month+'-'+d,program:'hafizlik',subject:'Aylık Hafızlık Takibi',work_value:codes.includes(v)?'':v,status_code:codes.includes(v)?(v==='İ'?'I':v):null,lesson_stage:stage,quality,note:old?.note||null}
 const {error}=await supabase.from('lesson_records').upsert(payload,{onConflict:'student_id,lesson_date,program,subject'});if(error)return setMsg(error.message);load()}
 return <section className="panel monthlyPanel hafLedger"><div className="panelHead"><div><h3>Hafızlık Aylık Takip Cetveli</h3><p>Kaçla gidiyor, Ham/Has/Tekrar ve günlük cüz-durum-kalite takibi.</p></div></div>{msg&&<div className="msg">{msg}</div>}<div className="tableWrap"><table className="monthTable"><thead><tr><th>Öğrenci</th><th>Kaçla Gidiyor</th><th>Ham / Has</th>{days.map(d=><th key={d}>{Number(d)}</th>)}</tr></thead><tbody>{list.map(st=>{const x=meta[st.id]||{};return <tr key={st.id}><td><b>{st.first_name} {st.last_name}</b></td><td><input className="cellInput tiny" value={x.pace||''} placeholder="Örn. 5" onChange={e=>setMeta({...meta,[st.id]:{...x,pace:e.target.value}})} onBlur={()=>saveMeta(st)}/></td><td><select className="attendanceSelect" value={x.stage||''} onChange={e=>{setMeta({...meta,[st.id]:{...x,stage:e.target.value}});setTimeout(()=>saveMeta({...st}),0)}}><option value="">—</option><option value="ham">Ham</option><option value="has">Has</option><option value="tekrar">Tekrar</option></select></td>{days.map(d=>{const r=cell(st.id,d),val=r?.status_code||(r?.work_value||'');return <td key={d} onClick={()=>editCell(st,d)} className={'hafCell '+(r?.quality||'')} title={r?.quality||'Kayıt için tıklayın'}><b>{val||'·'}</b>{r?.quality&&<small>{r.quality}</small>}</td>})}</tr>})}{!list.length&&<tr><td colSpan={days.length+3}>Bu hafızlık sınıfında öğrenci bulunmuyor.</td></tr>}</tbody></table></div><p className="muted">Kodlar: H Hasta · R Raporlu · İ İzinli · T Tatil · X Ders Vermedi · M Mazeret · G Gelmedi. Birden fazla cüz “7-8” şeklinde girilebilir.</p></section>
}