'use client'
import {useEffect,useMemo,useState} from 'react'
const qOpts=[['','·'],['saglam','S'],['iyi','İ'],['orta','O'],['zayif','Z']]
const statuses=['','H','R','İ','T','X','M','G']
export default function HafizlikDersCetveli({supabase,students,classes,profile}){
 const now=new Date(),[year,setYear]=useState(now.getFullYear()),[month,setMonth]=useState(now.getMonth()+1),[classId,setClassId]=useState(''),[rows,setRows]=useState([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState('')
 const hClasses=classes.filter(c=>c.program==='hafizlik')
 const list=useMemo(()=>students.filter(s=>s.status==='active'&&hClasses.some(c=>c.id===s.class_id)&&(!classId||s.class_id===classId)).sort((a,b)=>(a.first_name+' '+a.last_name).localeCompare(b.first_name+' '+b.last_name,'tr')),[students,classes,classId])
 const days=new Date(year,month,0).getDate(),prefix=year+'-'+String(month).padStart(2,'0')+'-'
 async function load(){const from=prefix+'01',to=prefix+String(days).padStart(2,'0');const {data}=await supabase.from('hafizlik_daily_records').select('*').gte('lesson_date',from).lte('lesson_date',to);setRows(data||[])}
 useEffect(()=>{load()},[year,month])
 const rec=(sid,d)=>rows.find(r=>r.student_id===sid&&r.lesson_date===prefix+String(d).padStart(2,'0'))
 async function saveState(st,field,value){const next={pace:parseInt(st.hafizlik_pace)||null,ham:st.hafizlik_ham_pages??null,hamhas:st.hafizlik_ham_has_pages??null,has:st.hafizlik_has_pages??null};next[field]=value===''?null:Number(value);setBusy(true);const {error}=await supabase.rpc('set_hafizlik_student_state',{p_student:st.id,p_pace:next.pace,p_ham:next.ham,p_ham_has:next.hamhas,p_has:next.has});setNotice(error?'Kaydedilemedi: '+error.message:'Hafızlık sayfa durumu kaydedildi.');if(!error){st.hafizlik_pace=next.pace;st.hafizlik_ham_pages=next.ham;st.hafizlik_ham_has_pages=next.hamhas;st.hafizlik_has_pages=next.has}setBusy(false)}
 async function saveCell(st,d,field,value){setBusy(true);setNotice('');const old=rec(st.id,d),date=prefix+String(d).padStart(2,'0'),cl=classes.find(c=>c.id===st.class_id);let payload={student_id:st.id,class_id:st.class_id,teacher_id:cl?.teacher_id||profile?.id,lesson_date:date,created_by:profile?.id,[field]:value||null};if(old)payload={...old,...payload,updated_at:new Date().toISOString()};const {error}=await supabase.from('hafizlik_daily_records').upsert(payload,{onConflict:'student_id,lesson_date'});if(error)setNotice('Kayıt hatası: '+error.message);await load();setBusy(false)}
 async function saveOutcome(st,d,value){setBusy(true);setNotice('');const old=rec(st.id,d),date=prefix+String(d).padStart(2,'0'),cl=classes.find(c=>c.id===st.class_id),isStatus=statuses.includes(value)&&value;const payload={student_id:st.id,class_id:st.class_id,teacher_id:cl?.teacher_id||profile?.id,lesson_date:date,created_by:profile?.id,work_value:old?.work_value||null,status_code:isStatus?value:null,quality:!isStatus&&value?value:null,lesson_stage:old?.lesson_stage||null,note:old?.note||null,updated_at:new Date().toISOString()};const {error}=await supabase.from('hafizlik_daily_records').upsert(payload,{onConflict:'student_id,lesson_date'});if(error)setNotice('Kayıt hatası: '+error.message);await load();setBusy(false)}
 return <div className="hafCetvelPage"><div className="hafCetvelHero"><div><small>E-GÖLKENT · HAFIZLIK TAKİP</small><h2>Hafızlık Ders Cetveli</h2><p>Aylık ders, cüz/has, kalite ve mazeret takibi</p></div><div className="hafFilters"><select value={year} onChange={e=>setYear(Number(e.target.value))}>{[year-1,year,year+1].map(y=><option key={y}>{y}</option>)}</select><select value={month} onChange={e=>setMonth(Number(e.target.value))}>{['Ocak','Şubat','Mart','Nisan','Mayıs','Haziran','Temmuz','Ağustos','Eylül','Ekim','Kasım','Aralık'].map((m,i)=><option key={m} value={i+1}>{m}</option>)}</select><select value={classId} onChange={e=>setClassId(e.target.value)}><option value="">Tüm Hafızlık Sınıfları</option>{hClasses.map(c=><option key={c.id} value={c.id}>{c.code} — {c.name}</option>)}</select></div></div>
 <div className="hafLegend"><span><b>1–20</b> Kaçla Gidiyor</span><span><b>H</b> Hasta</span><span><b>R</b> Raporlu</span><span><b>İ</b> İzinli</span><span><b>T</b> Tatil</span><span><b>M</b> Mazeret</span><span><b>G</b> Gelmedi</span><span><b>X</b> Ders Vermedi</span><span><b>S/İ/O/Z</b> Kalite</span></div>
 {notice&&<div className="hafNotice">{notice}</div>}<div className="hafTableWrap"><table className="hafTable"><thead><tr><th className="hafStudent">Öğrenci</th><th className="hafPace">Kaçla<br/>Gidiyor</th><th className="hafStage">Ham</th><th className="hafStage">Ham-Has</th><th className="hafStage">Has</th>{Array.from({length:days},(_,i)=><th key={i}>{i+1}</th>)}</tr></thead><tbody>{list.map((st,n)=><tr key={st.id}><td className="hafStudent"><b>{n+1}</b> {st.first_name} {st.last_name}</td><td><select defaultValue={parseInt(st.hafizlik_pace)||''} onChange={e=>saveState(st,'pace',e.target.value)} disabled={busy}><option value="">—</option>{Array.from({length:20},(_,i)=><option key={i+1} value={i+1}>{i+1}</option>)}</select></td><td><input className="hafStageInput" type="number" min="0" max="20" defaultValue={st.hafizlik_ham_pages??''} onBlur={e=>saveState(st,'ham',e.target.value)}/></td><td><input className="hafStageInput" type="number" min="0" max="20" defaultValue={st.hafizlik_ham_has_pages??''} onBlur={e=>saveState(st,'hamhas',e.target.value)}/></td><td><input className="hafStageInput" type="number" min="0" max="20" defaultValue={st.hafizlik_has_pages??''} onBlur={e=>saveState(st,'has',e.target.value)}/></td>{Array.from({length:days},(_,i)=>{const d=i+1,r=rec(st.id,d);return <td key={d} className={'hafDay '+(r?.quality||'')}><input className="hafWork" defaultValue={r?.work_value||''} placeholder="Cüz" onBlur={e=>saveCell(st,d,'work_value',e.target.value.trim())}/><select className={"hafOutcome "+(r?.quality||'')+" "+(r?.status_code?'status-'+r.status_code:'')} value={r?.status_code||r?.quality||''} onChange={e=>saveOutcome(st,d,e.target.value)}}><option value="">·</option><optgroup label="Ders Kalitesi">{qOpts.filter(x=>x[0]).map(([v,l])=><option key={v} value={v}>{l}</option>)}</optgroup><optgroup label="Durum">{statuses.filter(Boolean).map(x=><option key={x} value={x}>{x}</option>)}</optgroup></select></td>})}</tr>)}</tbody></table></div></div>
}