'use client'
import useLiveRefresh from '../hooks/useLiveRefresh'
import {useEffect,useMemo,useState} from 'react'
const qOpts=[['','·'],['saglam','S'],['iyi','Y'],['orta','O'],['zayif','Z']]
const statuses=['','H','R','İ','T','X','M','G']
export default function HafizlikDersCetveli({supabase,students,classes,profile,institution,permissions}){
 const canUpdate=profile?.role==='super_admin'||!!permissions?.can_update
 const [opClasses,setOpClasses]=useState([])
 const now=new Date(),academicYears=(()=>{const m=String(institution?.academic_year||'').match(/(\d{4})\D+(\d{4})/);return m?[Number(m[1]),Number(m[2])]:[now.getFullYear(),now.getFullYear()+1]})(),[year,setYear]=useState(academicYears.includes(now.getFullYear())?now.getFullYear():academicYears[0]),[month,setMonth]=useState(now.getMonth()+1),[classId,setClassId]=useState(''),[rows,setRows]=useState([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState('')
 useEffect(()=>{if(!academicYears.includes(year))setYear(academicYears[0])},[institution?.academic_year])
 useLiveRefresh(supabase,['hafizlik_daily_records','students'],load)
 const hClasses=classes.filter(c=>c.program==='hafizlik')
 useEffect(()=>{if(!profile?.id)return;Promise.all(classes.filter(c=>c.program==='hafizlik').map(async c=>{const {data}=await supabase.rpc('can_operate_class',{p_class_id:c.id,p_module:'hafizlik'});return data?c.id:null})).then(x=>setOpClasses(x.filter(Boolean)))},[profile?.id,classes,permissions])
 const list=useMemo(()=>students.filter(s=>s.status==='active'&&hClasses.some(c=>c.id===s.class_id)&&(!classId||s.class_id===classId)).sort((a,b)=>(a.first_name+' '+a.last_name).localeCompare(b.first_name+' '+b.last_name,'tr')),[students,classes,classId])
 const days=new Date(year,month,0).getDate(),prefix=year+'-'+String(month).padStart(2,'0')+'-'
 async function load(){const from=prefix+'01',to=prefix+String(days).padStart(2,'0');const {data}=await supabase.from('hafizlik_daily_records').select('*').gte('lesson_date',from).lte('lesson_date',to);setRows(data||[])}
 useEffect(()=>{load()},[year,month])
 const rec=(sid,d)=>rows.find(r=>r.student_id===sid&&r.lesson_date===prefix+String(d).padStart(2,'0'))
 async function saveState(st,field,value){if(!canUpdate||!opClasses.includes(st.class_id)){setNotice('Bu işlem için düzenleme yetkiniz bulunmuyor.');return}const next={pace:parseInt(st.hafizlik_pace)||null,ham:st.hafizlik_ham_pages??null,hamhas:st.hafizlik_ham_has_pages??null,has:st.hafizlik_has_pages??null};next[field]=value===''?null:Number(value);setBusy(true);const {error}=await supabase.rpc('set_hafizlik_student_state',{p_student:st.id,p_pace:next.pace,p_ham:next.ham,p_ham_has:next.hamhas,p_has:next.has});setNotice(error?'Kaydedilemedi: '+error.message:'Hafızlık sayfa durumu kaydedildi.');if(!error){st.hafizlik_pace=next.pace;st.hafizlik_ham_pages=next.ham;st.hafizlik_ham_has_pages=next.hamhas;st.hafizlik_has_pages=next.has}setBusy(false)}
 async function saveCell(st,d,field,value){if(!canUpdate||!opClasses.includes(st.class_id)){setNotice('Bu işlem için düzenleme yetkiniz bulunmuyor.');return}setBusy(true);setNotice('');const old=rec(st.id,d),date=prefix+String(d).padStart(2,'0'),cl=classes.find(c=>c.id===st.class_id);let payload={student_id:st.id,class_id:st.class_id,teacher_id:cl?.teacher_id||profile?.id,lesson_date:date,created_by:profile?.id,[field]:value||null};if(old)payload={...old,...payload,updated_at:new Date().toISOString()};const {error}=await supabase.from('hafizlik_daily_records').upsert(payload,{onConflict:'student_id,lesson_date'});if(error)setNotice('Kayıt hatası: '+error.message);await load();setBusy(false)}
 async function saveOutcome(st,d,value){if(!canUpdate||!opClasses.includes(st.class_id)){setNotice('Bu işlem için düzenleme yetkiniz bulunmuyor.');return}setBusy(true);setNotice('');const old=rec(st.id,d),date=prefix+String(d).padStart(2,'0'),cl=classes.find(c=>c.id===st.class_id),isStatus=Boolean(value)&&statuses.includes(value);const payload={student_id:st.id,class_id:st.class_id,teacher_id:cl?.teacher_id||profile?.id,lesson_date:date,created_by:profile?.id,work_value:old?.work_value||null,status_code:isStatus?value:null,quality:!isStatus&&value?value:null,lesson_stage:old?.lesson_stage||null,note:old?.note||null,updated_at:new Date().toISOString()};const {error}=await supabase.from('hafizlik_daily_records').upsert(payload,{onConflict:'student_id,lesson_date'});if(error)setNotice('Kayıt hatası: '+error.message);await load();setBusy(false)}

 async function saveHasText(st,value){if(!canUpdate||!opClasses.includes(st.class_id)){setNotice('Düzenleme yetkiniz bulunmuyor.');return}const text=value.trim();if(text.length>80){setNotice('Has bilgisi en fazla 80 karakter olabilir.');return}setBusy(true);const {error}=await supabase.rpc('set_hafizlik_has_stage_text',{p_student:st.id,p_value:text});if(!error)st.hafizlik_has_stage_text=text;setNotice(error?'Has bilgisi kaydedilemedi: '+error.message:'Has bilgisi kaydedildi.');setBusy(false)}

 async function saveCompactCell(st,d,raw){
  if(!canUpdate||!opClasses.includes(st.class_id)){setNotice('Düzenleme yetkiniz bulunmuyor.');return false}
  const input=raw.trim().toLocaleUpperCase('tr-TR'),old=rec(st.id,d);
  const qualityMap={S:'saglam',Y:'iyi',O:'orta',Z:'zayif'};
  const match=input.match(/^(.*?)\s*([SYOZ])$/u);
  const status=statuses.includes(input)&&input!==''?input:null;
  let work=input,quality=null;
  if(status){work=''}
  else if(match&&match[1].trim()){work=match[1].trim();quality=qualityMap[match[2]]}
  else if(input){work=input;quality=old?.quality||null}
  if(work.length>60){setNotice('Cüz bilgisi en fazla 60 karakter olabilir.');return false}
  if(!status&&work===String(old?.work_value||'').trim()&&quality===(old?.quality||null)&&!old?.status_code)return true;
  setBusy(true);setNotice('');
  const date=prefix+String(d).padStart(2,'0'),cl=classes.find(c=>c.id===st.class_id);
  const payload={student_id:st.id,class_id:st.class_id,teacher_id:cl?.teacher_id||profile?.id,lesson_date:date,created_by:profile?.id,work_value:work||null,status_code:status,quality:status?null:quality,lesson_stage:old?.lesson_stage||null,note:old?.note||null,updated_at:new Date().toISOString()};
  const {error}=await supabase.from('hafizlik_daily_records').upsert(payload,{onConflict:'student_id,lesson_date'});
  if(error){setNotice('Kayıt hatası: '+error.message);setBusy(false);return false}
  setRows(previous=>{const others=previous.filter(x=>!(x.student_id===st.id&&x.lesson_date===date));return [...others,{...old,...payload}]});
  setBusy(false);return true
 }
 const compactValue=r=>r?.status_code||r?.work_value||''
 const compactEditValue=r=>r?.status_code||[r?.work_value||'',{saglam:'S',iyi:'Y',orta:'O',zayif:'Z'}[r?.quality]||''].filter(Boolean).join(' ')
 return <div className="hafCetvelPage"><div className="hafCetvelHero"><div><small>E-GÖLKENT · HAFIZLIK TAKİP</small><h2>Hafızlık Ders Cetveli</h2><p>Tek hücrede cüz ve kalite: 7-8 S · 12 Y · 5 O · 3 Z</p></div><div className="hafFilters"><select value={year} onChange={e=>setYear(Number(e.target.value))}>{academicYears.map(y=><option key={y}>{y}</option>)}</select><select value={month} onChange={e=>setMonth(Number(e.target.value))}>{['Ocak','Şubat','Mart','Nisan','Mayıs','Haziran','Temmuz','Ağustos','Eylül','Ekim','Kasım','Aralık'].map((m,i)=><option key={m} value={i+1}>{m}</option>)}</select><select value={classId} onChange={e=>setClassId(e.target.value)}><option value="">Tüm Hafızlık Sınıfları</option>{hClasses.map(c=><option key={c.id} value={c.id}>{c.code} — {c.name}</option>)}</select></div></div>
 <div className="hafLegend"><span><b>1–20</b> Kaçla Gidiyor</span><span><b>H</b> Hasta</span><span><b>R</b> Raporlu</span><span><b>İ</b> İzinli</span><span><b>T</b> Tatil</span><span><b>M</b> Mazeret</span><span><b>G</b> Gelmedi</span><span><b>X</b> Ders Vermedi</span><span><b>S/Y/O/Z</b> Kalite</span></div>
 {notice&&<div className="hafNotice">{notice}</div>}<div className="hafTableWrap"><table className="hafTable"><thead><tr><th className="hafStudent">Öğrenci</th><th className="hafPace">Kaçla<br/>Gidiyor</th><th className="hafStage">Ham</th><th className="hafStage">Ham-Has</th><th className="hafStage">Has</th>{Array.from({length:days},(_,i)=><th key={i}>{i+1}</th>)}</tr></thead><tbody>{list.map((st,n)=><tr key={st.id}><td className="hafStudent"><b>{n+1}</b>{st.photo_url?<img className="lessonStudentPhoto" src={st.photo_url} alt="" />:<span className="lessonStudentPhoto lessonStudentInitial">{(st.first_name||'?').charAt(0)}</span>}<span>{st.first_name} {st.last_name}</span></td><td><select defaultValue={parseInt(st.hafizlik_pace)||''} onChange={e=>saveState(st,'pace',e.target.value)} disabled={busy||!opClasses.includes(st.class_id)}><option value="">—</option>{Array.from({length:20},(_,i)=><option key={i+1} value={i+1}>{i+1}</option>)}</select></td><td><input className="hafStageInput" type="number" min="0" max="20" defaultValue={st.hafizlik_ham_pages??''} onBlur={e=>saveState(st,'ham',e.target.value)} disabled={!opClasses.includes(st.class_id)}/></td><td><input className="hafStageInput" type="number" min="0" max="20" defaultValue={st.hafizlik_ham_has_pages??''} onBlur={e=>saveState(st,'hamhas',e.target.value)} disabled={!opClasses.includes(st.class_id)}/></td><td><input className="hafStageInput hafHasText" type="text" maxLength={80} title="Örnek: 1. Has, 2. Has veya 20" placeholder="1. Has" defaultValue={st.hafizlik_has_stage_text??(st.hafizlik_has_pages??'')} onBlur={e=>{if(e.target.value.trim()!==String(st.hafizlik_has_stage_text??(st.hafizlik_has_pages??'')))saveHasText(st,e.target.value)}} disabled={!opClasses.includes(st.class_id)}/></td>{Array.from({length:days},(_,i)=>{const d=i+1,r=rec(st.id,d);return <td key={d} className={'hafDay '+(r?.quality||'')+(r?.status_code?' status-'+r.status_code:'')} title={r?.quality?'Kalite: '+r.quality:'Örnek: 7-8 S'}><input className="hafCompactInput" key={st.id+'-'+d+'-'+(r?.updated_at||'')} defaultValue={compactValue(r)} placeholder="·" onFocus={e=>{e.currentTarget.value=compactEditValue(r);e.currentTarget.select()}} onBlur={async e=>{const el=e.currentTarget,value=el.value;if(value.trim()===compactEditValue(r)){el.value=compactValue(r);return}const ok=await saveCompactCell(st,d,value);if(!ok)el.value=compactValue(r)}} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();if(e.key==='Escape'){e.currentTarget.value=compactValue(r);e.currentTarget.blur()}}} disabled={busy||!opClasses.includes(st.class_id)}/></td>})}</tr>)}</tbody></table></div></div>
}