'use client'
import {useEffect,useMemo,useState} from 'react'
const qualities=[['saglam','S','Sağlam'],['iyi','İ','İyi'],['orta','O','Orta'],['zayif','Z','Zayıf']]
const statuses=[['H','Hasta'],['R','Raporlu'],['İ','İzinli'],['T','Tatil'],['M','Mazeretli'],['G','Gelmedi'],['X','Ders Vermedi']]
const months=['Ocak','Şubat','Mart','Nisan','Mayıs','Haziran','Temmuz','Ağustos','Eylül','Ekim','Kasım','Aralık']
export default function KapDersCetveli({supabase,students,classes,profiles,profile}){
 const now=new Date(),[drafts,setDrafts]=useState({}),[year,setYear]=useState(now.getFullYear()),[month,setMonth]=useState(now.getMonth()+1),[rows,setRows]=useState([]),[reviews,setReviews]=useState([]),[teacherFilter,setTeacherFilter]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[detail,setDetail]=useState(null),[reviewStudent,setReviewStudent]=useState(null)
 const isManager=['super_admin','admin'].includes(profile?.role),kapClassIds=classes.filter(c=>c.program==='kap').map(c=>c.id),teachers=(profiles||[]).filter(p=>p.active!==false&&['teacher','admin','super_admin'].includes(p.role))
 const list=useMemo(()=>students.filter(s=>s.status==='active'&&kapClassIds.includes(s.class_id)&&(!teacherFilter||s.kap_teacher_id===teacherFilter)).sort((a,b)=>(a.first_name+' '+a.last_name).localeCompare(b.first_name+' '+b.last_name,'tr')),[students,classes,teacherFilter])
 const days=new Date(year,month,0).getDate(),prefix=year+'-'+String(month).padStart(2,'0')+'-'
 async function load(){const [{data:r},{data:v}]=await Promise.all([supabase.from('kap_daily_records').select('*,creator:created_by(full_name),updater:updated_by(full_name)').gte('lesson_date',prefix+'01').lte('lesson_date',prefix+String(days).padStart(2,'0')),supabase.from('kap_hatim_reviews').select('*').eq('year',year).eq('month',month)]);setRows(r||[]);setReviews(v||[])}
 useEffect(()=>{load()},[year,month])
 const rec=(sid,d)=>rows.find(r=>r.student_id===sid&&r.lesson_date===prefix+String(d).padStart(2,'0')),parseJuz=v=>[...new Set(String(v||'').split(/[^0-9]+/).filter(Boolean).map(Number).filter(n=>n>=1&&n<=30))],juzText=r=>(r?.juz_values?.length?r.juz_values:(r?.juz_no?[r.juz_no]:[])).join(', '),teacherName=id=>teachers.find(t=>t.id===id)?.full_name||'Takip eden öğretici atanmadı',canEdit=st=>isManager||st.kap_teacher_id===profile?.id
 const studentRows=sid=>rows.filter(r=>r.student_id===sid),reviewFor=st=>reviews.find(r=>r.student_id===st.id&&r.has_no===Number(st.kap_has_no))
 const summary=useMemo(()=>{const q={saglam:0,iyi:0,orta:0,zayif:0},s={H:0,R:0,'İ':0,T:0,M:0,G:0,X:0};rows.forEach(r=>{if(r.quality)q[r.quality]=(q[r.quality]||0)+1;if(r.status_code)s[r.status_code]=(s[r.status_code]||0)+1});return {cuz:rows.reduce((n,r)=>n+(r.juz_values?.length||(r.juz_no?1:0)),0),hatim:reviews.filter(r=>r.completed_at).length,q,s}},[rows,reviews])
 async function setState(st,teacher,has){setBusy(true);const clearing=!has,{error}=await supabase.rpc('set_kap_student_state',{p_student:st.id,p_teacher:teacher||null,p_has:has?Number(has):null});setNotice(error?'Kaydedilemedi: '+error.message:clearing?'Has kaldırıldı; öğrenciye ait KAP cüz kayıtları ve hatim değerlendirmeleri temizlendi.':'Öğrenci takip bilgisi güncellendi.');if(!error){st.kap_teacher_id=teacher||null;st.kap_has_no=has?Number(has):null;if(clearing){setRows(x=>x.filter(r=>r.student_id!==st.id));setReviews(x=>x.filter(r=>r.student_id!==st.id));setDrafts(x=>{const n={...x};Object.keys(n).filter(k=>k.startsWith(st.id+'-')).forEach(k=>delete n[k]);return n})}}setBusy(false)}
 async function save(st,d,patch){if(!canEdit(st))return false;const old=rec(st.id,d),date=prefix+String(d).padStart(2,'0'),juz=patch.juz_values!==undefined?patch.juz_values:(old?.juz_values?.length?old.juz_values:(old?.juz_no?[old.juz_no]:[])),quality=patch.quality!==undefined?patch.quality:(old?.quality||null),status=patch.status_code!==undefined?patch.status_code:(old?.status_code||null);setBusy(true);setNotice('');const {error}=await supabase.rpc('save_kap_daily_record',{p_student:st.id,p_date:date,p_juz_values:juz,p_quality:quality,p_status:status,p_note:old?.note||null});if(error){setNotice('Kayıt hatası: '+error.message);setBusy(false);return false}await load();setBusy(false);return true}
 async function saveReview(e){e.preventDefault();const st=reviewStudent.student,fd=new FormData(e.currentTarget),old=reviewFor(st),payload={student_id:st.id,teacher_id:st.kap_teacher_id,year,month,has_no:Number(st.kap_has_no),completed_at:fd.get('completed_at')||null,overall_quality:fd.get('overall_quality')||null,teacher_opinion:fd.get('teacher_opinion')||null,development_note:fd.get('development_note')||null,created_by:old?.created_by||profile.id,updated_by:profile.id,updated_at:new Date().toISOString()};setBusy(true);const {error}=await supabase.from('kap_hatim_reviews').upsert(payload,{onConflict:'student_id,year,month,has_no'});setNotice(error?'Değerlendirme kaydedilemedi: '+error.message:'Hatim sonu değerlendirmesi kaydedildi.');setReviewStudent(null);await load();setBusy(false)}
 return <div className="kapPremium"><div className="kapHero"><div><small>E-GÖLKENT · KUR’AN’I ANLAMA PROGRAMI</small><h2>KAP Ders Cetveli</h2><p>Has, cüz, ders kalitesi ve öğretici sorumluluğunu tek ekranda yönetin.</p></div><div className="kapFilters"><select value={year} onChange={e=>setYear(+e.target.value)}>{[now.getFullYear()-1,now.getFullYear(),now.getFullYear()+1].map(y=><option key={y}>{y}</option>)}</select><select value={month} onChange={e=>setMonth(+e.target.value)}>{months.map((m,i)=><option value={i+1} key={m}>{m}</option>)}</select><select value={teacherFilter} onChange={e=>setTeacherFilter(e.target.value)}><option value="">Tüm Takip Eden Öğreticiler</option>{teachers.map(t=><option value={t.id} key={t.id}>{t.full_name}</option>)}</select></div></div>
 <div className="kapKpis"><div><small>Aktif KAP Öğrencisi</small><b>{list.length}</b></div><div><small>Bu Ay Okunan Cüz</small><b>{summary.cuz}</b></div><div><small>Tamamlanan Hatim</small><b>{summary.hatim}</b></div><div><small>Sağlam / İyi</small><b>{summary.q.saglam+summary.q.iyi}</b></div><div><small>Ders Vermedi</small><b>{summary.s.X}</b></div></div>
 <div className="kapLegend">{qualities.map(x=><span key={x[0]}><b>{x[1]}</b>{x[2]}</span>)}{statuses.map(x=><span key={x[0]}><b>{x[0]}</b>{x[1]}</span>)}</div>{notice&&<div className="hafNotice">{notice}</div>}
 <div className="kapTableWrap"><table className="kapTable"><thead><tr><th className="kapStudent">Öğrenci</th><th className="kapTeacher">Takip Eden Öğretici</th><th className="kapHas">Has</th><th className="kapReviewCol">Hatim</th>{Array.from({length:days},(_,i)=><th key={i}>{i+1}</th>)}</tr></thead><tbody>{list.map((st,n)=>{const rv=reviewFor(st);return <tr key={st.id} className={!canEdit(st)?'kapLocked':''}><td className="kapStudent"><b>{n+1}</b><div><strong>{st.first_name} {st.last_name}</strong><small>{studentRows(st.id).reduce((n,x)=>n+(x.juz_values?.length||(x.juz_no?1:0)),0)} cüz · {rv?.completed_at?'Hatim tamamlandı':!canEdit(st)?'Salt görüntüleme':'Takipte'}</small></div></td><td className="kapTeacher">{isManager?<select value={st.kap_teacher_id||''} disabled={busy} onChange={e=>setState(st,e.target.value,st.kap_has_no)}><option value="">Atanmamış</option>{teachers.map(t=><option key={t.id} value={t.id}>{t.full_name}</option>)}</select>:<span>{teacherName(st.kap_teacher_id)}</span>}</td><td className="kapHas"><input type="number" min="1" value={st.kap_has_no||''} disabled={!canEdit(st)||busy} onChange={e=>{st.kap_has_no=e.target.value;setState(st,st.kap_teacher_id,e.target.value)}}/></td><td className="kapReviewCol"><button className={rv?.completed_at?'done':''} disabled={!canEdit(st)} onClick={()=>{if(!st.kap_has_no){setNotice('Hatim değerlendirmesi için önce öğrencinin Has numarasını giriniz.');return}setReviewStudent({student:st})}}>{rv?.completed_at?'✓ Değerlendirildi':'Değerlendir'}</button></td>{Array.from({length:days},(_,i)=>{const d=i+1,r=rec(st.id,d),out=r?.quality||r?.status_code||'';return <td key={d} className={'kapDay '+(r?.quality||'')+(r?.status_code==='X'?' x':'')}><input type="text" inputMode="numeric" placeholder="1, 2" value={drafts[st.id+'-'+d]??juzText(r)} disabled={!canEdit(st)||busy||!st.kap_has_no||!!r?.status_code} onChange={e=>setDrafts(x=>({...x,[st.id+'-'+d]:e.target.value}))} onBlur={async e=>{const key=st.id+'-'+d,v=parseJuz(e.target.value),previous=juzText(r);const ok=await save(st,d,{juz_values:v});setDrafts(x=>{const n={...x};if(ok)delete n[key];else n[key]=previous;return n})}}/><select value={out} disabled={!canEdit(st)||busy||!st.kap_has_no} onChange={e=>{const v=e.target.value,isQ=qualities.some(q=>q[0]===v);if(v&&!isQ){const key=st.id+'-'+d;setDrafts(x=>({...x,[key]:''}));save(st,d,{status_code:v,quality:null,juz_values:[]})}else save(st,d,{quality:v||null,status_code:null})}}><option value="">·</option><optgroup label="Ders Kalitesi">{qualities.map(q=><option key={q[0]} value={q[0]}>{q[1]} — {q[2]}</option>)}</optgroup><optgroup label="Durum">{statuses.map(s=><option key={s[0]} value={s[0]}>{s[0]} — {s[1]}</option>)}</optgroup></select>{r&&<button title="İşlem bilgisi" onClick={()=>setDetail({...r,student:st})}>i</button>}</td>})}</tr>})}</tbody></table></div>
 {isManager&&<section className="kapMonthlyReport"><div className="kapReportHead"><div><small>YÖNETİCİ RAPORU</small><h3>{months[month-1]} {year} · KAP Aylık Eğitim Özeti</h3></div><b>{list.length} Öğrenci</b></div><div className="kapReportGrid"><div><span>Okunan Cüz</span><strong>{summary.cuz}</strong></div><div><span>Hatim Tamamlayan</span><strong>{summary.hatim}</strong></div><div><span>Sağlam</span><strong>{summary.q.saglam}</strong></div><div><span>İyi</span><strong>{summary.q.iyi}</strong></div><div><span>Orta</span><strong>{summary.q.orta}</strong></div><div><span>Zayıf</span><strong>{summary.q.zayif}</strong></div></div><div className="kapReportStudents">{list.map(st=>{const rr=studentRows(st.id),rv=reviewFor(st);return <div key={st.id}><div><b>{st.first_name} {st.last_name}</b><small>{teacherName(st.kap_teacher_id)} · {st.kap_has_no?st.kap_has_no+'. Has':'Has girilmedi'}</small></div><span>{rr.reduce((n,x)=>n+(x.juz_values?.length||(x.juz_no?1:0)),0)} cüz</span><span>{rr.filter(x=>x.quality==='saglam').length} S</span><span>{rr.filter(x=>x.quality==='iyi').length} İ</span><em className={rv?.completed_at?'ok':''}>{rv?.completed_at?'Hatim ✓':'Devam'}</em></div>})}</div></section>}
 {reviewStudent&&(()=>{const st=reviewStudent.student,rv=reviewFor(st);return <div className="kapModalShade" onClick={()=>setReviewStudent(null)}><form className="kapReviewCard" onSubmit={saveReview} onClick={e=>e.stopPropagation()}><small>HATİM SONU DEĞERLENDİRMESİ</small><h3>{st.first_name} {st.last_name}</h3><p>{st.kap_has_no}. Has · {months[month-1]} {year} · {teacherName(st.kap_teacher_id)}</p><div className="kapReviewForm"><label>Hatim Tamamlanma Tarihi<input name="completed_at" type="date" defaultValue={rv?.completed_at||''}/></label><label>Genel Okuma Kalitesi<select name="overall_quality" defaultValue={rv?.overall_quality||''}><option value="">Seçiniz</option>{qualities.map(q=><option value={q[0]} key={q[0]}>{q[2]}</option>)}</select></label><label className="wide">Öğretici Kanaati<textarea name="teacher_opinion" defaultValue={rv?.teacher_opinion||''} placeholder="Öğrencinin hatim sürecine ilişkin genel kanaat..."/></label><label className="wide">Gelişim ve Takip Notu<textarea name="development_note" defaultValue={rv?.development_note||''} placeholder="Bir sonraki Has için dikkat edilecek hususlar..."/></label></div><div className="kapReviewActions"><button type="button" onClick={()=>setReviewStudent(null)}>Vazgeç</button><button className="primary" disabled={busy}>Değerlendirmeyi Kaydet</button></div></form></div>})()}
 {detail&&<div className="kapModalShade" onClick={()=>setDetail(null)}><div className="kapAuditCard" onClick={e=>e.stopPropagation()}><small>KAYIT DETAYI</small><h3>{detail.student.first_name} {detail.student.last_name}</h3><div><span>Tarih</span><b>{new Date(detail.lesson_date+'T12:00:00').toLocaleDateString('tr-TR')}</b></div><div><span>Cüz</span><b>{detail.juz_no||'—'}</b></div><div><span>İlk kaydeden</span><b>{detail.creator?.full_name||'—'}</b></div><div><span>Son işlem</span><b>{detail.updater?.full_name||detail.creator?.full_name||'—'}</b></div><div><span>Güncelleme</span><b>{new Date(detail.updated_at).toLocaleString('tr-TR')}</b></div><button onClick={()=>setDetail(null)}>Kapat</button></div></div>}
 </div>
}