'use client'
import {useEffect,useMemo,useState} from 'react'
import {BookOpen,Search,Plus,ArrowRightLeft,RotateCcw} from 'lucide-react'
export default function LibraryModule({supabase,students,profile,permissions,institution}){
 const canCreate=profile?.role==='super_admin'||!!permissions?.can_create,canUpdate=profile?.role==='super_admin'||!!permissions?.can_update
 const [books,setBooks]=useState([]),[copies,setCopies]=useState([]),[loans,setLoans]=useState([]),[personnel,setPersonnel]=useState([]),[q,setQ]=useState(''),[showAdd,setShowAdd]=useState(false),[showDesk,setShowDesk]=useState(false),[showInventory,setShowInventory]=useState(false),[copyBook,setCopyBook]=useState(null),[borrowerKind,setBorrowerKind]=useState('student'),[notice,setNotice]=useState('')
 async function load(){const [{data:b},{data:c},{data:l},{data:p}]=await Promise.all([supabase.from('library_books').select('*').eq('active',true).order('title'),supabase.from('library_copies').select('*'),supabase.from('library_loans').select('*').is('returned_at',null),supabase.from('personnel').select('id,first_name,last_name').eq('active',true).order('first_name')]);setBooks(b||[]);setCopies(c||[]);setLoans(l||[]);setPersonnel(p||[])}
 useEffect(()=>{load()},[])
 const filtered=useMemo(()=>books.filter(b=>(b.title+' '+(b.author||'')+' '+(b.isbn||'')+' '+(b.category||'')).toLocaleLowerCase('tr').includes(q.toLocaleLowerCase('tr'))),[books,q])
 const overdue=loans.filter(l=>new Date(l.due_date+'T23:59:59')<new Date()).length
 async function checkout(e){e.preventDefault();const f=new FormData(e.currentTarget),kind=f.get('kind'),borrower=f.get('borrower');const {error}=await supabase.rpc('library_checkout',{p_copy:f.get('copy'),p_student:kind==='student'?borrower:null,p_personnel:kind==='personnel'?borrower:null,p_due:f.get('due'),p_note:f.get('note')||null});setNotice(error?'Ödünç verilemedi: '+error.message:'Kitap başarıyla ödünç verildi.');if(!error){e.currentTarget.reset();await load()}}
 async function returnLoan(id){const {error}=await supabase.rpc('library_return',{p_loan:id,p_condition:null,p_note:null});setNotice(error?'İade alınamadı: '+error.message:'Kitap iade alındı.');if(!error)await load()}
 async function setCopyStatus(id,status){const {error}=await supabase.rpc('library_set_copy_status',{p_copy:id,p_status:status,p_note:null});setNotice(error?'Durum değiştirilemedi: '+error.message:'Kopya durumu güncellendi.');if(!error)await load()}

 async function addBook(e){e.preventDefault();const f=new FormData(e.currentTarget),title=String(f.get('title')||'').trim();if(!title)return;const {data:b,error}=await supabase.from('library_books').insert({institution_id:institution.id,title,author:f.get('author')||null,publisher:f.get('publisher')||null,isbn:f.get('isbn')||null,category:f.get('category')||null,shelf_location:f.get('shelf')||null,created_by:profile.id}).select().single();if(error)return setNotice(error.message);const count=Math.max(1,Number(f.get('count'))||1),stamp=Date.now().toString().slice(-7);const rows=Array.from({length:count},(_,i)=>({book_id:b.id,asset_code:'KT-'+stamp+'-'+String(i+1).padStart(2,'0')}));const {error:ce}=await supabase.from('library_copies').insert(rows);if(ce)setNotice('Kitap eklendi; kopya oluşturulamadı: '+ce.message);else setNotice('Kitap ve '+count+' kopya eklendi.');setShowAdd(false);load()}
 return <div className="libraryPage"><section className="libraryHero"><div><small>E-GÖLKENT · KÜTÜPHANE YÖNETİMİ</small><h2>Kütüphane Yönetimi</h2><p>Katalog, envanter, ödünç ve iade işlemleri tek merkezde.</p></div><div className="libraryHeroActions">{canUpdate&&<button onClick={()=>setShowInventory(!showInventory)}><BookOpen size={17}/> Envanter</button>}{canUpdate&&<button onClick={()=>setShowDesk(!showDesk)}><ArrowRightLeft size={17}/> Ödünç / İade</button>}{canCreate&&<button onClick={()=>setShowAdd(!showAdd)}><Plus size={17}/> Yeni Kitap</button>}</div></section>
 <div className="libraryKpis"><div><BookOpen/><span>Toplam Eser<b>{books.length}</b></span></div><div><span>Toplam Kopya<b>{copies.length}</b></span></div><div><ArrowRightLeft/><span>Ödünçte<b>{loans.length}</b></span></div><div className={overdue?'warn':''}><span>Geciken<b>{overdue}</b></span></div><div><span>Rafta<b>{copies.filter(x=>x.status==='available').length}</b></span></div></div>
 {showInventory&&<section className="libraryInventory"><div className="libraryInventoryHead"><div><small>FİZİKÎ KİTAP ENVANTERİ</small><h3>Kopya / Demirbaş Yönetimi</h3></div><b>{copies.length} kopya</b></div><div className="libraryCopyList">{copies.map(cp=>{const b=books.find(x=>x.id===cp.book_id);return <div key={cp.id}><span><b>{b?.title||'Kitap'}</b><small>{cp.asset_code}{cp.barcode?' · '+cp.barcode:''}</small></span><select disabled={!canUpdate||cp.status==='loaned'} value={cp.status} onChange={e=>setCopyStatus(cp.id,e.target.value)}><option value="available">Rafta</option><option value="loaned">Ödünçte</option><option value="reserved">Rezerve</option><option value="lost">Kayıp</option><option value="damaged">Hasarlı</option><option value="maintenance">Bakımda</option></select></div>})}</div></section>}
 {showDesk&&<section className="libraryDesk"><div><h3>Ödünç Ver</h3><form onSubmit={checkout}><select name="kind" value={borrowerKind} onChange={e=>setBorrowerKind(e.target.value)}><option value="student">Öğrenci</option><option value="personnel">Personel</option></select><select name="borrower" key={borrowerKind} required><option value="">{borrowerKind==='student'?'Öğrenci seçiniz':'Personel seçiniz'}</option>{borrowerKind==='student'?students.map(s=><option key={s.id} value={s.id}>{s.first_name} {s.last_name}</option>):personnel.map(p=><option key={p.id} value={p.id}>{p.first_name} {p.last_name}</option>)}</select><select name="copy" required><option value="">Raftaki kitap / kopya</option>{copies.filter(x=>x.status==='available').map(x=>{const b=books.find(b=>b.id===x.book_id);return <option key={x.id} value={x.id}>{b?.title||'Kitap'} · {x.asset_code}</option>})}</select><input name="due" type="date" required/><input name="note" placeholder="Not (isteğe bağlı)"/><button>Ödünç Ver</button></form></div><div><h3>Açık Ödünçler</h3><div className="libraryOpenLoans">{loans.map(l=>{const cp=copies.find(x=>x.id===l.copy_id),b=books.find(x=>x.id===cp?.book_id),st=students.find(x=>x.id===l.student_id),pe=personnel.find(x=>x.id===l.personnel_id);return <div key={l.id}><span><b>{b?.title||'Kitap'}</b><small>{st?st.first_name+' '+st.last_name:pe?pe.first_name+' '+pe.last_name:'Kullanıcı'} · Son: {l.due_date}</small></span>{canUpdate&&<button onClick={()=>returnLoan(l.id)}><RotateCcw size={14}/> İade</button>}</div>})}{!loans.length&&<p>Açık ödünç kaydı yok.</p>}</div></div></section>}
 {showAdd&&<form className="libraryAdd" onSubmit={addBook}><input name="title" required placeholder="Kitap adı"/><input name="author" placeholder="Yazar"/><input name="publisher" placeholder="Yayınevi"/><input name="isbn" placeholder="ISBN / Barkod"/><input name="category" placeholder="Kategori"/><input name="shelf" placeholder="Raf / Dolap"/><input name="count" type="number" min="1" defaultValue="1" placeholder="Adet"/><button disabled={!canCreate}>Kaydet</button></form>}
 {notice&&<div className="libraryNotice">{notice}</div>}
 <section className="libraryPanel"><div className="libraryToolbar"><div><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Kitap, yazar, ISBN veya kategori ara..."/></div><b>{filtered.length} eser</b></div>
 <div className="libraryGrid">{filtered.map(b=>{const bc=copies.filter(c=>c.book_id===b.id),avail=bc.filter(c=>c.status==='available').length;return <article key={b.id}><div className="bookCover">{b.cover_url?<img src={b.cover_url} alt=""/>:<BookOpen size={28}/>}</div><div><small>{b.category||'GENEL'}</small><h3>{b.title}</h3><p>{b.author||'Yazar belirtilmedi'}</p><span>{b.shelf_location||'Raf belirtilmedi'}</span><footer><b>{avail} rafta</b><em>{bc.length} kopya</em>{canUpdate&&<button type="button" onClick={()=>setCopyBook(copyBook===b.id?null:b.id)}>Kopyalar</button>}</footer>{copyBook===b.id&&<div className="libraryCopies">{bc.map(cp=><div key={cp.id}><code>{cp.asset_code}</code><select value={cp.status} disabled={cp.status==='loaned'} onChange={e=>setCopyStatus(cp.id,e.target.value)}><option value="available">Rafta</option><option value="loaned">Ödünçte</option><option value="reserved">Rezerve</option><option value="lost">Kayıp</option><option value="damaged">Hasarlı</option><option value="maintenance">Bakımda</option></select></div>)}</div>}</div></article>})}{!filtered.length&&<div className="libraryEmpty">Henüz katalog kaydı bulunmuyor.</div>}</div></section>
 </div>
}
