'use client'
import {useEffect,useMemo,useState} from 'react'
import {BookOpen,Search,Plus,ArrowRightLeft,RotateCcw} from 'lucide-react'
export default function LibraryModule({supabase,students,profile,permissions,institution}){
 const canCreate=profile?.role==='super_admin'||!!permissions?.can_create,canUpdate=profile?.role==='super_admin'||!!permissions?.can_update
 const [books,setBooks]=useState([]),[copies,setCopies]=useState([]),[loans,setLoans]=useState([]),[q,setQ]=useState(''),[showAdd,setShowAdd]=useState(false),[notice,setNotice]=useState('')
 async function load(){const [{data:b},{data:c},{data:l}]=await Promise.all([supabase.from('library_books').select('*').eq('active',true).order('title'),supabase.from('library_copies').select('*'),supabase.from('library_loans').select('*').is('returned_at',null)]);setBooks(b||[]);setCopies(c||[]);setLoans(l||[])}
 useEffect(()=>{load()},[])
 const filtered=useMemo(()=>books.filter(b=>(b.title+' '+(b.author||'')+' '+(b.isbn||'')+' '+(b.category||'')).toLocaleLowerCase('tr').includes(q.toLocaleLowerCase('tr'))),[books,q])
 const overdue=loans.filter(l=>new Date(l.due_date+'T23:59:59')<new Date()).length
 async function addBook(e){e.preventDefault();const f=new FormData(e.currentTarget),title=String(f.get('title')||'').trim();if(!title)return;const {data:b,error}=await supabase.from('library_books').insert({institution_id:institution.id,title,author:f.get('author')||null,publisher:f.get('publisher')||null,isbn:f.get('isbn')||null,category:f.get('category')||null,shelf_location:f.get('shelf')||null,created_by:profile.id}).select().single();if(error)return setNotice(error.message);const count=Math.max(1,Number(f.get('count'))||1),stamp=Date.now().toString().slice(-7);const rows=Array.from({length:count},(_,i)=>({book_id:b.id,asset_code:'KT-'+stamp+'-'+String(i+1).padStart(2,'0')}));const {error:ce}=await supabase.from('library_copies').insert(rows);if(ce)setNotice('Kitap eklendi; kopya oluşturulamadı: '+ce.message);else setNotice('Kitap ve '+count+' kopya eklendi.');setShowAdd(false);load()}
 return <div className="libraryPage"><section className="libraryHero"><div><small>E-GÖLKENT · KÜTÜPHANE YÖNETİMİ</small><h2>Kütüphane Yönetimi</h2><p>Katalog, envanter, ödünç ve iade işlemleri tek merkezde.</p></div>{canCreate&&<button onClick={()=>setShowAdd(!showAdd)}><Plus size={17}/> Yeni Kitap</button>}</section>
 <div className="libraryKpis"><div><BookOpen/><span>Toplam Eser<b>{books.length}</b></span></div><div><span>Toplam Kopya<b>{copies.length}</b></span></div><div><ArrowRightLeft/><span>Ödünçte<b>{loans.length}</b></span></div><div className={overdue?'warn':''}><span>Geciken<b>{overdue}</b></span></div><div><span>Rafta<b>{copies.filter(x=>x.status==='available').length}</b></span></div></div>
 {showAdd&&<form className="libraryAdd" onSubmit={addBook}><input name="title" required placeholder="Kitap adı"/><input name="author" placeholder="Yazar"/><input name="publisher" placeholder="Yayınevi"/><input name="isbn" placeholder="ISBN / Barkod"/><input name="category" placeholder="Kategori"/><input name="shelf" placeholder="Raf / Dolap"/><input name="count" type="number" min="1" defaultValue="1" placeholder="Adet"/><button disabled={!canCreate}>Kaydet</button></form>}
 {notice&&<div className="libraryNotice">{notice}</div>}
 <section className="libraryPanel"><div className="libraryToolbar"><div><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Kitap, yazar, ISBN veya kategori ara..."/></div><b>{filtered.length} eser</b></div>
 <div className="libraryGrid">{filtered.map(b=>{const bc=copies.filter(c=>c.book_id===b.id),avail=bc.filter(c=>c.status==='available').length;return <article key={b.id}><div className="bookCover">{b.cover_url?<img src={b.cover_url} alt=""/>:<BookOpen size={28}/>}</div><div><small>{b.category||'GENEL'}</small><h3>{b.title}</h3><p>{b.author||'Yazar belirtilmedi'}</p><span>{b.shelf_location||'Raf belirtilmedi'}</span><footer><b>{avail} rafta</b><em>{bc.length} kopya</em></footer></div></article>})}{!filtered.length&&<div className="libraryEmpty">Henüz katalog kaydı bulunmuyor.</div>}</div></section>
 </div>
}
