'use client'
import {useEffect,useState} from 'react'
export default function OperationsHub({supabase,students,profiles,session}){
 const tabs=['Disiplin','İzin / Çıkış','Yatakhane','Nöbet','Kantin / Muhasebe','Bildirim'],[tab,setTab]=useState('Disiplin'),[rows,setRows]=useState([]),[msg,setMsg]=useState(''),[form,setForm]=useState({})
 const table={Disiplin:'student_discipline','İzin / Çıkış':'student_leaves',Yatakhane:'dormitory_assignments',Nöbet:'duty_roster','Kantin / Muhasebe':'finance_entries',Bildirim:'notifications'}[tab]
 async function load(){const {data,error}=await supabase.from(table).select('*').order(tab==='Nöbet'?'duty_date':tab==='Kantin / Muhasebe'?'entry_date':'created_at',{ascending:false});if(error)setMsg(error.message);else setRows(data||[])}
 useEffect(()=>{load();setForm({});setMsg('')},[tab])
 const studentOptions=<>{students.map(s=><option key={s.id} value={s.id}>{s.first_name} {s.last_name}</option>)}</>
 async function save(e){e.preventDefault();let p={}
  if(tab==='Disiplin')p={student_id:form.student_id,incident_date:form.date,category:form.category,description:form.description,action_taken:form.action||null,recorded_by:session.user.id}
  if(tab==='İzin / Çıkış')p={student_id:form.student_id,leave_type:form.type||'izin',start_at:form.start,end_at:form.end||null,reason:form.reason||null,guardian_name:form.guardian||null,guardian_phone:form.phone||null,recorded_by:session.user.id}
  if(tab==='Yatakhane')p={student_id:form.student_id,floor:form.floor||null,room_no:form.room||null,bed_no:form.bed||null,note:form.note||null,updated_by:session.user.id}
  if(tab==='Nöbet')p={duty_date:form.date,duty_type:form.type||'belletmen',user_id:form.user_id,start_time:form.start||null,end_time:form.end||null,note:form.note||null,created_by:session.user.id}
  if(tab==='Kantin / Muhasebe')p={entry_date:form.date,entry_type:form.type,category:form.category,amount:Number(form.amount),student_id:form.student_id||null,description:form.description||null,recorded_by:session.user.id}
  if(tab==='Bildirim')p={title:form.title,body:form.body,audience:form.audience||'all',published:!!form.published,created_by:session.user.id}
  const q=tab==='Yatakhane'?supabase.from(table).upsert(p,{onConflict:'student_id'}):supabase.from(table).insert(p);const {error}=await q;if(error)return setMsg(error.message);setMsg('Kayıt başarıyla kaydedildi.');setForm({});load()
 }
 const studentName=id=>{const s=students.find(x=>x.id===id);return s?s.first_name+' '+s.last_name:'—'},userName=id=>profiles.find(x=>x.id===id)?.full_name||'—'
 return <><section className="panel"><div className="panelHead"><div><h3>Kurum İşlemleri</h3><p>İdari süreçleri GEYS üzerinden kayıt altına alın.</p></div></div><div className="opsTabs">{tabs.map(x=><button className={tab===x?'primary':'ghost'} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div></section>{msg&&<div className="msg">{msg}</div>}<section className="panel"><h3>{tab} — Yeni Kayıt</h3><form className="institutionForm" onSubmit={save}>
 {['Disiplin','İzin / Çıkış','Yatakhane'].includes(tab)&&<label>Öğrenci<select required value={form.student_id||''} onChange={e=>setForm({...form,student_id:e.target.value})}><option value="">Seçiniz</option>{studentOptions}</select></label>}
 {tab==='Disiplin'&&<><label>Tarih<input required type="date" value={form.date||''} onChange={e=>setForm({...form,date:e.target.value})}/></label><label>Kategori<input required value={form.category||''} onChange={e=>setForm({...form,category:e.target.value})}/></label><label className="wide">Olay / Açıklama<textarea required value={form.description||''} onChange={e=>setForm({...form,description:e.target.value})}/></label><label className="wide">Uygulanan İşlem<textarea value={form.action||''} onChange={e=>setForm({...form,action:e.target.value})}/></label></>}
 {tab==='İzin / Çıkış'&&<><label>Çıkış<input required type="datetime-local" value={form.start||''} onChange={e=>setForm({...form,start:e.target.value})}/></label><label>Dönüş<input type="datetime-local" value={form.end||''} onChange={e=>setForm({...form,end:e.target.value})}/></label><label>Veli / Teslim Alan<input value={form.guardian||''} onChange={e=>setForm({...form,guardian:e.target.value})}/></label><label>Telefon<input value={form.phone||''} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label className="wide">Sebep<textarea value={form.reason||''} onChange={e=>setForm({...form,reason:e.target.value})}/></label></>}
 {tab==='Yatakhane'&&<><label>Kat<input value={form.floor||''} onChange={e=>setForm({...form,floor:e.target.value})}/></label><label>Oda No<input value={form.room||''} onChange={e=>setForm({...form,room:e.target.value})}/></label><label>Yatak No<input value={form.bed||''} onChange={e=>setForm({...form,bed:e.target.value})}/></label><label>Not<input value={form.note||''} onChange={e=>setForm({...form,note:e.target.value})}/></label></>}
 {tab==='Nöbet'&&<><label>Görevli<select required value={form.user_id||''} onChange={e=>setForm({...form,user_id:e.target.value})}><option value="">Seçiniz</option>{profiles.filter(x=>x.active).map(x=><option key={x.id} value={x.id}>{x.full_name}</option>)}</select></label><label>Tarih<input required type="date" value={form.date||''} onChange={e=>setForm({...form,date:e.target.value})}/></label><label>Başlangıç<input type="time" value={form.start||''} onChange={e=>setForm({...form,start:e.target.value})}/></label><label>Bitiş<input type="time" value={form.end||''} onChange={e=>setForm({...form,end:e.target.value})}/></label><label className="wide">Görev Notu<textarea value={form.note||''} onChange={e=>setForm({...form,note:e.target.value})}/></label></>}
 {tab==='Kantin / Muhasebe'&&<><label>İşlem<select required value={form.type||''} onChange={e=>setForm({...form,type:e.target.value})}><option value="">Seçiniz</option><option value="income">Gelir</option><option value="expense">Gider</option><option value="student_credit">Öğrenci Bakiye Yükleme</option><option value="student_debit">Öğrenci Harcama/Borç</option></select></label><label>Tarih<input required type="date" value={form.date||''} onChange={e=>setForm({...form,date:e.target.value})}/></label><label>Kategori<input required value={form.category||''} onChange={e=>setForm({...form,category:e.target.value})}/></label><label>Tutar<input required type="number" step="0.01" min="0" value={form.amount||''} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>Öğrenci (opsiyonel)<select value={form.student_id||''} onChange={e=>setForm({...form,student_id:e.target.value})}><option value="">—</option>{studentOptions}</select></label><label>Açıklama<input value={form.description||''} onChange={e=>setForm({...form,description:e.target.value})}/></label></>}
 {tab==='Bildirim'&&<><label>Başlık<input required value={form.title||''} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Hedef<select value={form.audience||'all'} onChange={e=>setForm({...form,audience:e.target.value})}><option value="all">Tümü</option><option value="teachers">Eğitmenler</option><option value="parents">Veliler</option><option value="students">Öğrenciler</option></select></label><label className="wide">Mesaj<textarea required value={form.body||''} onChange={e=>setForm({...form,body:e.target.value})}/></label><label><input type="checkbox" checked={!!form.published} onChange={e=>setForm({...form,published:e.target.checked})}/> Yayınla</label></>}
 <button className="primary">Kaydet</button></form></section><section className="panel tablePanel"><h3>Son Kayıtlar</h3><div className="tableWrap"><table><thead><tr><th>Tarih / Kayıt</th><th>Kişi / Öğrenci</th><th>Tür / Başlık</th><th>Açıklama</th></tr></thead><tbody>{rows.slice(0,50).map(r=><tr key={r.id}><td>{r.incident_date||r.duty_date||r.entry_date||r.start_at?.slice(0,16)||r.updated_at?.slice(0,10)||r.created_at?.slice(0,10)}</td><td>{r.student_id?studentName(r.student_id):r.user_id?userName(r.user_id):'—'}</td><td>{r.category||r.duty_type||r.entry_type||r.title||r.leave_type||((r.floor||'')+' / '+(r.room_no||''))}</td><td>{r.description||r.reason||r.note||r.body||r.action_taken||'—'}</td></tr>)}{!rows.length&&<tr><td colSpan="4">Henüz kayıt yok.</td></tr>}</tbody></table></div></section></>
}