'use client'
import {useEffect,useState} from 'react'
const types={suggestion:'Öneri',request:'Talep',complaint:'Şikâyet',thanks:'Teşekkür / Memnuniyet',technical:'Teknik Sorun',other:'Diğer'}
const statuses={new:'Alındı',reviewing:'İnceleniyor',assigned:'İlgili Birimde',answered:'Cevaplandı',resolved:'Sonuçlandırıldı',closed:'Kapatıldı'}
export default function ParentSupport({supabase,data,challengeId,sessionTc}){
 const [open,setOpen]=useState(false),[rows,setRows]=useState([]),[type,setType]=useState('suggestion'),[subject,setSubject]=useState(''),[description,setDescription]=useState(''),[privateMode,setPrivateMode]=useState(false),[complained,setComplained]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('')
 async function load(){if(!data?.student?.id||!challengeId)return;const {data:r}=await supabase.rpc('parent_support_requests',{p_student_id:data.student.id,p_challenge_id:challengeId,p_tc:sessionTc});if(r?.ok)setRows(r.requests||[])}
 useEffect(()=>{load()},[data?.student?.id,challengeId,sessionTc])
 async function submit(e){e.preventDefault();setBusy(true);setNotice('');const {data:r,error}=await supabase.rpc('parent_create_support_request',{p_student_id:data.student.id,p_challenge_id:challengeId,p_tc:sessionTc,p_request_type:type,p_subject:subject,p_description:description,p_privacy_mode:privateMode,p_complained_name:type==='complaint'?complained:null});setBusy(false);if(error||!r?.ok)return setNotice(r?.message||'Başvuru gönderilemedi.');setNotice('Başvurunuz alındı. Takip numaranız: '+r.tracking_no);setSubject('');setDescription('');setComplained('');setPrivateMode(false);setOpen(false);load()}
 return <section className="parentSection parentSupport"><div className="parentSupportHead"><div><small>E-GÖLKENT İLETİŞİM MERKEZİ</small><h4>Talep · Öneri · Şikâyet</h4><p>Görüşlerinizi yönetime doğrudan iletebilir, başvurunuzun durumunu buradan takip edebilirsiniz.</p></div><button onClick={()=>setOpen(!open)}>{open?'Formu Kapat':'+ Yeni Başvuru'}</button></div>
 {notice&&<div className="parentSupportNotice">{notice}</div>}
 {open&&<form className="parentSupportForm" onSubmit={submit}><label>Başvuru Türü<select value={type} onChange={e=>setType(e.target.value)}>{Object.entries(types).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>{type==='complaint'&&<label>Şikâyet Edilen Kişi / Birim<input value={complained} onChange={e=>setComplained(e.target.value)} placeholder="Kişi adı veya ilgili birim"/></label>}<label className="wide">Konu<input value={subject} onChange={e=>setSubject(e.target.value)} minLength="3" maxLength="160" required placeholder="Başvurunuzu kısaca özetleyiniz"/></label><label className="wide">Açıklama<textarea value={description} onChange={e=>setDescription(e.target.value)} minLength="10" maxLength="5000" rows="5" required placeholder="Talep, öneri veya şikâyetinizi açıkça yazınız…"/></label><label className="parentPrivacy wide"><input type="checkbox" checked={privateMode} onChange={e=>setPrivateMode(e.target.checked)}/><span><b>Kimliğimi Gizle</b><small>Bu seçeneği işaretlediğinizde başvurunuz gizli olarak işleme alınır. Başvuru sahibi bilgileri, başvurunun yönlendirildiği kişi veya kişilerle paylaşılmaz.</small></span></label><div className="parentSupportSubmit wide"><span>Gönderilen başvuruya otomatik takip numarası verilir.</span><button disabled={busy}>{busy?'Gönderiliyor…':'Başvuruyu Gönder'}</button></div></form>}
 <div className="parentSupportHistory"><div className="parentSupportHistoryTitle"><b>Başvurularım</b><span>{rows.length} kayıt</span></div>{!rows.length?<p className="muted">Henüz oluşturulmuş bir başvurunuz bulunmuyor.</p>:rows.map(r=><article key={r.id}><header><div><span>{types[r.request_type]||r.request_type}</span>{r.privacy_mode&&<em>🔒 Kimliği Gizli</em>}</div><strong>{statuses[r.status]||r.status}</strong></header><h5>{r.subject}</h5><p>{r.description}</p>{r.request_type==='complaint'&&r.complained_name&&<small>İlgili kişi / birim: {r.complained_name}</small>}<footer><b>{r.tracking_no}</b><time>{new Date(r.created_at).toLocaleString('tr-TR')}</time></footer>{(r.messages||[]).length>0&&<div className="parentSupportAnswers">{r.messages.map((m,i)=><div key={i}><b>{m.author_type==='management'?'Yönetim Cevabı':'Mesaj'}</b><p>{m.body}</p><small>{new Date(m.created_at).toLocaleString('tr-TR')}</small></div>)}</div>}</article>)}</div></section>
}