'use client'
import {useMemo,useState} from 'react'

const trQuality=v=>({saglam:'Sağlam',iyi:'İyi',orta:'Orta',zayif:'Zayıf'}[v]||v||'—')
const trStatus=v=>({H:'Hasta',R:'Raporlu','İ':'İzinli',T:'Tatil',M:'Mazeret',G:'Gelmedi',X:'Ders Vermedi'}[v]||v||'—')
const fmt=d=>new Date(d+'T12:00:00').toLocaleDateString('tr-TR',{day:'2-digit',month:'long',year:'numeric'})
export default function ParentProgress({data}){
 const program=data?.class?.program||'kap',student=data?.student||{}
 const academic=String(data?.institution?.academic_year||'').match(/(\d{4})\D+(\d{4})/)
 const now=new Date(),defaultMonth=now.toISOString().slice(0,7)
 const [selectedMonth,setSelectedMonth]=useState(defaultMonth)
 const monthOptions=useMemo(()=>{const out=[];if(academic){const a=+academic[1],b=+academic[2];for(let m=9;m<=12;m++)out.push(a+'-'+String(m).padStart(2,'0'));for(let m=1;m<=8;m++)out.push(b+'-'+String(m).padStart(2,'0'))}else{for(let i=0;i<12;i++){const d=new Date(now.getFullYear(),now.getMonth()-i,1);out.push(d.toISOString().slice(0,7))}}return out},[data?.institution?.academic_year])
 const month=monthOptions.includes(selectedMonth)?selectedMonth:(monthOptions.find(x=>x===defaultMonth)||monthOptions[0]||defaultMonth)
 const [yearNo,monthNo]=month.split('-').map(Number),days=new Date(yearNo,monthNo,0).getDate(),prefix=month+'-'
 const inMonth=(r,key='lesson_date')=>String(r?.[key]||'').startsWith(prefix)
 const lessons=(data?.lessons||[]).filter(r=>inMonth(r)),attendance=(data?.attendance||[]).filter(r=>inMonth(r,'attendance_date'))
 const yuzune=(data?.yuzune_progress||[]).filter(r=>inMonth(r)),hafizlik=(data?.hafizlik_records||[]).filter(r=>inMonth(r)),kap=(data?.kap_records||[]).filter(r=>inMonth(r))
 const records=program==='hafizlik'?hafizlik:program==='yuzune'?yuzune:kap
 const last=records[0]||lessons[0]
 const title=program==='hafizlik'?'Hafızlık Ders ve Ezber Takibi':program==='yuzune'?'Yüzüne Kur’an Okuma Takibi':'Kur’an’ı Anlama (KAP) Takibi'
 const monthLabel=new Date(yearNo,monthNo-1,1).toLocaleDateString('tr-TR',{month:'long',year:'numeric'})
 return <section className="parentSection parentProgress">
  <div className="parentProgressHead"><div><h4>Aylık Eğitim Takibi</h4><p>{title}</p></div><label className="parentMonthSelect"><span>Ay Seçiniz</span><select value={month} onChange={e=>setSelectedMonth(e.target.value)}>{monthOptions.map(x=><option key={x} value={x}>{new Date(+x.slice(0,4),+x.slice(5)-1,1).toLocaleDateString('tr-TR',{month:'long',year:'numeric'})}</option>)}</select></label></div>
  <div className="progressSummary"><div><small>Seçili Dönem</small><b>{monthLabel}</b></div><div><small>Ders Kaydı</small><b>{records.length}</b></div><div><small>Devamsızlık / Mazeret</small><b>{attendance.filter(x=>x.status!=='present').length}</b></div>{program==='hafizlik'&&<div><small>Son Cüz / Has</small><b>{last?.work_value||'—'}</b></div>}{program==='yuzune'&&<div><small>Son Ders</small><b>{last?.title||last?.curriculum_stage||'—'}</b></div>}{program==='kap'&&<><div><small>Son Dinletilen Cüz</small><b>{last?.juz_values?.length?last.juz_values.join(', ')+(last.juz_values.length>1?' Cüzler':' Cüz'):last?.juz_no?last.juz_no+'. Cüz':'—'}</b></div><div><small>Mevcut Has</small><b>{student.kap_has_no?student.kap_has_no+'. Has':'—'}</b></div></>}</div>
  <div className="monthStrip">{Array.from({length:days},(_,i)=>i+1).map(day=>{const date=prefix+String(day).padStart(2,'0'),lesson=records.find(x=>x.lesson_date===date),att=attendance.find(x=>x.attendance_date===date),absent=att&&att.status!=='present';return <div key={day} className={'monthDay'+(lesson?' hasLesson':'')+(absent?' absentDay':'')}><b>{day}</b><span>{lesson?'✓':absent?'G':'·'}</span></div>})}</div>
  {program==='hafizlik'&&<div className="parentHafizlik"><div className="parentYuzuneTitle"><h4>Hafızlık Dersleri</h4><span>{hafizlik.length} kayıt</span></div><div className="parentHafSummary"><div><small>Kaçla Gidiyor</small><b>{student.hafizlik_pace||'—'}</b></div><div><small>Ham</small><b>{student.hafizlik_ham_pages??'—'}</b></div><div><small>Ham-Has</small><b>{student.hafizlik_ham_has_pages??'—'}</b></div><div><small>Has</small><b>{student.hafizlik_has_pages??'—'}</b></div></div>{!hafizlik.length?<p className="parentEmpty">Bu ay Hafızlık ders kaydı bulunmuyor.</p>:<div className="parentHafList">{hafizlik.map((r,n)=><div className={'parentHafRow '+(r.quality||'')} key={n}><div><b>{r.work_value?('Cüz / Has: '+r.work_value):'Ders Durumu'}</b><small>{fmt(r.lesson_date)} · {r.lesson_stage||'Ders'}</small></div><strong>{r.status_code||'✓'}</strong><span>{r.status_code?trStatus(r.status_code):trQuality(r.quality)}</span></div>)}</div>}</div>}
  {program==='yuzune'&&<div className="parentYuzuneHistory"><div className="parentYuzuneTitle"><h4>Yüzüne · Ders / Sûre / Dua Takibi</h4><span>{yuzune.length} kayıt</span></div>{!yuzune.length?<p className="parentEmpty">Bu ay Yüzüne ders kaydı bulunmuyor.</p>:<div className="parentYuzuneList">{yuzune.map((r,n)=><div className={'parentYuzuneRow '+(r.quality||'')} key={n}><div><b>{r.title||'Kur’an-ı Kerim'}</b><small>{fmt(r.lesson_date)} · Verilen ders / sûre / dua</small></div><span className={'parentResult '+r.result}>{r.result==='plus'?'+':'−'}</span><strong>{r.result==='minus'?'Tekrar':trQuality(r.quality)}</strong></div>)}</div>}</div>}
  {program==='kap'&&<div className="parentHafizlik"><div className="parentYuzuneTitle"><h4>KAP · Hocaya Dinletilen Cüzler</h4><span>{kap.length} kayıt</span></div>{!kap.length?<p className="parentEmpty">Bu ay KAP ders kaydı bulunmuyor.</p>:<div className="parentHafList">{kap.map((r,n)=><div className={'parentHafRow '+(r.quality||'')} key={n}><div><b>{r.juz_values?.length?r.juz_values.map(x=>x+'. Cüz').join(' · '):r.juz_no?r.juz_no+'. Cüz':'KAP Dersi'}</b><small>{fmt(r.lesson_date)} · {r.has_no||student.kap_has_no||'—'}. Has{data?.kap_teacher?.full_name?' · '+data.kap_teacher.full_name:''}</small></div><strong>{r.status_code||'✓'}</strong><span>{r.status_code?trStatus(r.status_code):trQuality(r.quality)}</span></div>)}</div>}</div>}
 </section>
}
