'use client'
import {useEffect,useMemo,useState} from 'react'
import * as XLSX from 'xlsx'
import {Document,Packer,Paragraph,Table,TableCell,TableRow,TextRun,WidthType,HeadingLevel,AlignmentType,ShadingType} from 'docx'
import {jsPDF} from 'jspdf'
import autoTable from 'jspdf-autotable'
const empty={first_name:'',last_name:'',category:'teacher',title:'',personnel_no:'',registry_no:'',phone:'',phone_secondary:'',email:'',birth_date:'',marital_status:'',employment_type:'',start_date:'',education:'',graduation:'',address:'',emergency_contact_name:'',emergency_contact_phone:'',blood_type:'',notes:'',active:true}
const labels={teacher:'Kur’an Kursu Hocaları',belletmen:'Belletmen Hocalar',administration:'İdari Personel',support:'Destek Personeli',other:'Diğer Personel'}
export default function PersonnelModule({supabase,session,institution,profile}){
 const [rows,setRows]=useState([]),[form,setForm]=useState(empty),[edit,setEdit]=useState(null),[q,setQ]=useState(''),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false),manager=['admin','super_admin'].includes(profile?.role)
 const load=async()=>{const {data,error}=await supabase.from('personnel').select('*').order('category').order('first_name');if(error)setMsg(error.message);else setRows(data||[])}
 useEffect(()=>{load()},[])
 const filtered=useMemo(()=>rows.filter(x=>(x.first_name+' '+x.last_name+' '+(x.title||'')+' '+(x.registry_no||'')).toLocaleLowerCase('tr').includes(q.toLocaleLowerCase('tr'))),[rows,q])
 async function save(e){e.preventDefault();if(!manager)return;setBusy(true);const x=edit||form,p={...x,institution_id:institution?.id||null,birth_date:x.birth_date||null,start_date:x.start_date||null,end_date:x.end_date||null,marital_status:x.marital_status||null,updated_by:session.user.id};delete p.id;delete p.created_at;delete p.updated_at;let r;if(edit)r=await supabase.from('personnel').update(p).eq('id',edit.id);else r=await supabase.from('personnel').insert({...p,created_by:session.user.id});setBusy(false);setMsg(r.error?r.error.message:'Personel kaydı başarıyla kaydedildi.');if(!r.error){setForm(empty);setEdit(null);load()}}
 async function remove(x){if(!manager||!confirm(x.first_name+' '+x.last_name+' personel kaydı silinsin mi?'))return;const {error}=await supabase.from('personnel').delete().eq('id',x.id);setMsg(error?error.message:'Personel kaydı silindi.');if(!error)load()}
 const simple=()=>({name:'Personel İsim Listesi',headers:['Ad Soyad','Personel Grubu','Ünvan','Telefon'],rows:filtered.map(x=>[x.first_name+' '+x.last_name,labels[x.category],x.title||'—',x.phone||'—'])})
 const detailed=()=>({name:'Personel Ayrıntılı Bilgi',headers:['Ad Soyad','Grup','Ünvan','Personel No','Sicil No','Telefon','2. Telefon','E-posta','Doğum Tarihi','Medeni Durum','İstihdam','Göreve Başlama','Eğitim','Mezuniyet','Kan Grubu','Acil Durum Kişisi','Acil Telefon','Adres','Durum'],rows:filtered.map(x=>[x.first_name+' '+x.last_name,labels[x.category],x.title||'—',x.personnel_no||'—',x.registry_no||'—',x.phone||'—',x.phone_secondary||'—',x.email||'—',x.birth_date||'—',x.marital_status==='married'?'Evli':x.marital_status==='single'?'Bekâr':'—',x.employment_type||'—',x.start_date||'—',x.education||'—',x.graduation||'—',x.blood_type||'—',x.emergency_contact_name||'—',x.emergency_contact_phone||'—',x.address||'—',x.active?'Aktif':'Pasif'])})
 function excel(r){const ws=XLSX.utils.aoa_to_sheet([['E-GÖLKENT'],[institution?.name||'Gölkent Erkek Yatılı Hafızlık Kur’an Kursu'],[r.name],[],r.headers,...r.rows]),wb=XLSX.utils.book_new();ws['!cols']=r.headers.map((h,i)=>({wch:Math.max(14,Math.min(32,Math.max(h.length,...r.rows.map(x=>String(x[i]||'').length))+2))}));XLSX.utils.book_append_sheet(wb,ws,'Personel');XLSX.writeFile(wb,'E-GOLKENT-'+r.name.replaceAll(' ','-')+'.xlsx')}
 async function word(r){const head=r.headers.map(x=>new TableCell({shading:{fill:'276B78',type:ShadingType.CLEAR},children:[new Paragraph({children:[new TextRun({text:x,bold:true,color:'FFFFFF'})]})]})),body=r.rows.map(row=>new TableRow({children:row.map(v=>new TableCell({children:[new Paragraph(String(v??''))]}))}));const doc=new Document({sections:[{children:[new Paragraph({text:'E-GÖLKENT',heading:HeadingLevel.TITLE,alignment:AlignmentType.CENTER}),new Paragraph({text:institution?.name||'',alignment:AlignmentType.CENTER}),new Paragraph({text:r.name,heading:HeadingLevel.HEADING_1}),new Paragraph({text:'Toplam Personel: '+r.rows.length}),new Table({width:{size:100,type:WidthType.PERCENTAGE},rows:[new TableRow({children:head}),...body]})]}]});const blob=await Packer.toBlob(doc),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='E-GOLKENT-'+r.name.replaceAll(' ','-')+'.docx';a.click();URL.revokeObjectURL(a.href)}
 function pdf(r){const doc=new jsPDF({orientation:r.headers.length>6?'landscape':'portrait'});doc.setFontSize(17);doc.text('E-GOLKENT',14,15);doc.setFontSize(11);doc.text(r.name,14,23);doc.setFontSize(8);doc.text('Toplam Personel: '+r.rows.length,14,29);autoTable(doc,{startY:34,head:[r.headers],body:r.rows,styles:{fontSize:r.headers.length>10?5.5:8,cellPadding:1.6},headStyles:{fillColor:[39,107,120]},alternateRowStyles:{fillColor:[242,247,248]}});doc.save('E-GOLKENT-'+r.name.replaceAll(' ','-')+'.pdf')}
 const groups=Object.keys(labels)
 return <div className="personnelModule"><section className="panel"><div className="panelHead"><div><small>E-GÖLKENT · PERSONEL BİLGİ SİSTEMİ</small><h3>Personel Yönetimi</h3><p>Kur’an kursu öğreticileri, belletmenler, idari ve destek personeli tek merkezde.</p></div><span className="countBadge">{rows.filter(x=>x.active).length} aktif</span></div><div className="personnelStats">{groups.map(k=><div key={k}><span>{labels[k]}</span><b>{rows.filter(x=>x.category===k&&x.active).length}</b></div>)}</div></section>
 {manager&&<section className="panel"><div className="panelHead"><div><h3>{edit?'Personel Kaydını Düzenle':'Yeni Personel Kaydı'}</h3><p>Kurumsal personel özlük ve iletişim bilgileri.</p></div>{edit&&<button className="ghost" onClick={()=>setEdit(null)}>Vazgeç</button>}</div><form className="personnelForm" onSubmit={save}>{[['first_name','Ad'],['last_name','Soyad'],['title','Ünvan / Görev'],['personnel_no','Personel No'],['registry_no','Sicil No'],['phone','Telefon'],['phone_secondary','2. Telefon'],['email','E-posta'],['education','Eğitim Durumu'],['graduation','Mezuniyet / Bölüm'],['employment_type','Çalışma Şekli'],['blood_type','Kan Grubu'],['emergency_contact_name','Acil Durum Kişisi'],['emergency_contact_phone','Acil Durum Telefonu']].map(([k,l])=><label key={k}>{l}<input required={k==='first_name'||k==='last_name'} value={(edit||form)[k]||''} onChange={e=>(edit?setEdit:setForm)({...edit||form,[k]:e.target.value})}/></label>)}<label>Personel Grubu<select value={(edit||form).category} onChange={e=>(edit?setEdit:setForm)({...edit||form,category:e.target.value})}>{groups.map(k=><option key={k} value={k}>{labels[k]}</option>)}</select></label><label>Doğum Tarihi<input type="date" value={(edit||form).birth_date||''} onChange={e=>(edit?setEdit:setForm)({...edit||form,birth_date:e.target.value})}/></label><label>Medeni Durum<select value={(edit||form).marital_status||''} onChange={e=>(edit?setEdit:setForm)({...edit||form,marital_status:e.target.value})}><option value="">Belirtilmedi</option><option value="single">Bekâr</option><option value="married">Evli</option></select></label><label>Göreve Başlama<input type="date" value={(edit||form).start_date||''} onChange={e=>(edit?setEdit:setForm)({...edit||form,start_date:e.target.value})}/></label><label className="wide">Adres<textarea value={(edit||form).address||''} onChange={e=>(edit?setEdit:setForm)({...edit||form,address:e.target.value})}/></label><label className="wide">Not<textarea value={(edit||form).notes||''} onChange={e=>(edit?setEdit:setForm)({...edit||form,notes:e.target.value})}/></label><label className="check"><input type="checkbox" checked={(edit||form).active} onChange={e=>(edit?setEdit:setForm)({...edit||form,active:e.target.checked})}/> Aktif personel</label><button className="primary" disabled={busy}>{busy?'Kaydediliyor…':'Personeli Kaydet'}</button></form>{msg&&<div className="msg">{msg}</div>}</section>}
 <section className="panel"><div className="panelHead"><div><h3>Personel Listesi</h3><p>Gruplandırılmış personel listesi ve kurumsal raporlar.</p></div><input placeholder="Personel ara…" value={q} onChange={e=>setQ(e.target.value)}/></div><div className="personnelExport"><b>İsim Listesi:</b><button onClick={()=>excel(simple())}>Excel</button><button onClick={()=>word(simple())}>Word</button><button onClick={()=>pdf(simple())}>PDF</button><b>Ayrıntılı Bilgi:</b><button onClick={()=>excel(detailed())}>Excel</button><button onClick={()=>word(detailed())}>Word</button><button onClick={()=>pdf(detailed())}>PDF</button></div>{groups.map(k=>{const list=filtered.filter(x=>x.category===k);return list.length?<div className="personnelGroup" key={k}><h4>{labels[k]} <span>{list.length}</span></h4><div className="tableWrap"><table><thead><tr><th>Ad Soyad</th><th>Ünvan</th><th>Sicil No</th><th>Telefon</th><th>Durum</th>{manager&&<th>İşlem</th>}</tr></thead><tbody>{list.map(x=><tr key={x.id}><td><b>{x.first_name} {x.last_name}</b></td><td>{x.title||'—'}</td><td>{x.registry_no||'—'}</td><td>{x.phone||'—'}</td><td>{x.active?'Aktif':'Pasif'}</td>{manager&&<td><div className="rowActions"><button className="ghost compact" onClick={()=>setEdit({...x})}>Düzenle</button><button className="danger compact" onClick={()=>remove(x)}>Sil</button></div></td>}</tr>)}</tbody></table></div></div>:null})}</section></div>
}