'use client'
import useLiveRefresh from '../hooks/useLiveRefresh'
import {useEffect,useState} from 'react'
const types={suggestion:'Öneri',request:'Talep',complaint:'Şikâyet',thanks:'Teşekkür / Memnuniyet',technical:'Teknik Sorun',other:'Diğer'}
const statuses={new:'Alındı',reviewing:'İnceleniyor',assigned:'İlgili Birimde',answered:'Cevaplandı',resolved:'Sonuçlandırıldı',closed:'Kapatıldı'}
export default function StaffSupport({supabase,profile,profiles,institution}){
 const [rows,setRows]=useState([]),[open,setOpen]=useState(false),[type,setType]=useState('suggestion'),[subject,setSubject]=useState(''),[description,setDescription]=useState(''),[privacy,setPrivacy]=useState(false),[complainedId,setComplainedId]=useState(''),[complainedName,setComplainedName]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('')
 async function load(){if(!profile?.id)return;const {data}=await supabase.from('support_requests').select('*,support_request_messages(body,author_type,created_at,internal_note)').eq('requester_profile_id',profile.id).order('created_at',{ascending:false});setRows(data||[])}
 useEffect(()=>{load()},[profile?.id])
 useLiveRefresh(supabase,['support_requests','support_request_messages'],load)
 async function submit(e){e.preventDefault();setBusy(true);setNotice('');const cp=profiles.find(x=>x.id===complainedId);const {data,error}=await supabase.from('support_requests').insert({institution_id:institution?.id,source_type:'personnel',requester_profile_id:profile.id,request_type:type,subject:subject.trim(),description:description.trim(),privacy_mode:privacy,complained_profile_id:type==='complaint'&&complainedId?complainedId:null,complained_name:type==='complaint'?(cp?.full_name||complainedName.trim()||null):null}).select('tracking_no').single();setBusy(false);if(error)return setNotice('Başvuru gönderilemedi: '+error.message);setNotice('Başvurunuz alındı. Takip numaranız: '+data.tracking_no);setSubject('');setDescription('');setPrivacy(false);setComplainedId('');setComplainedName('');setOpen(false);load()}
 return <div className="staffSupport"><div className="staffSupportIntro"><div><small>PERSONEL İLETİŞİM KANALI</small><h3>Görüşünüzü Güvenle İletin</h3><p>Talep, öneri veya şikâyetinizi kayıt altına alın ve sonucunu tek ekrandan takip edin.</p></div><button onClick={()=>setOpen(!open)}>{open?'Formu Kapat':'+ Yeni Başvuru'}</button></div>{notice&&<div className="parentSupportNotice">{notice}</div>}{open&&<form className="parentSupportForm" onSubmit={submit}><label>Başvuru Türü<select value={type} onChange={e=>setType(e.target.value)}>{Object.entries(types).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>{type==='complaint'&&<label>Şikâyet Edilen<select value={complainedId} onChange={e=>setComplainedId(e.target.value)}><option value="">Kişi seçiniz / diğer</option>{profiles.filter(p=>p.id!==profile.id).map(p=><option key={p.id} value={p.id}>{p.full_name}</option>)}</select></label>}{type==='complaint'&&!complainedId&&<label className="wide">Kişi / Birim<input value={complainedName} onChange={e=>setComplainedName(e.target.value)} placeholder="Listede yoksa kişi veya birim yazınız"/></label>}<label className="wide">Konu<input value={subject} onChange={e=>setSubject(e.target.value)} minLength="3" maxLength="160" required/></label><label className="wide">Açıklama<textarea rows="5" value={description} onChange={e=>setDescription(e.target.value)} minLength="10" maxLength="5000" required/></label><label className="parentPrivacy wide"><input type="checkbox" checked={privacy} onChange={e=>setPrivacy(e.target.checked)}/><span><b>Kimliğimi Gizle</b><small>Bu seçeneği işaretlediğinizde başvurunuz gizli olarak işleme alınır. Başvuru sahibi bilgileri, başvurunun yönlendirildiği kişi veya kişilerle paylaşılmaz.</small></span></label><div className="parentSupportSubmit wide"><span>Başvurunuz kayıt altına alınarak takip numarası oluşturulur.</span><button disabled={busy}>{busy?'Gönderiliyor…':'Başvuruyu Gönder'}</button></div></form>}<div className="staffSupportHistory"><h4>Başvurularım <span>{rows.length}</span></h4>{!rows.length?<div className="supportEmpty">Henüz başvurunuz bulunmuyor.</div>:rows.map(r=><article key={r.id}><header><div><span>{types[r.request_type]}</span>{r.privacy_mode&&<em>🔒 Kimliği Gizli</em>}</div><strong>{statuses[r.status]||r.status}</strong></header><h5>{r.subject}</h5><p>{r.description}</p><footer><b>{r.tracking_no}</b><time>Başvuru: {new Date(r.created_at).toLocaleString('tr-TR')}</time></footer>{r.updated_at&&r.updated_at!==r.created_at&&<div className="supportLastUpdate">Son güncelleme: {new Date(r.updated_at).toLocaleString('tr-TR')}</div>}{(r.support_request_messages||[]).filter(m=>!m.internal_note).map((m,i)=><div className="staffAnswer" key={i}><b>{m.author_type==='management'?'✓ Yönetim Cevabı':'Mesaj'}</b><p>{m.body}</p><small>{new Date(m.created_at).toLocaleString('tr-TR')}</small></div>)}</article>)}</div></div>
}