'use client'
import {useEffect,useMemo,useState} from 'react'
const types={suggestion:'Öneri',request:'Talep',complaint:'Şikâyet',thanks:'Teşekkür / Memnuniyet',technical:'Teknik Sorun',other:'Diğer'}
const statuses={new:'Yeni',reviewing:'İnceleniyor',assigned:'Yönlendirildi',answered:'Cevaplandı',resolved:'Sonuçlandırıldı',closed:'Kapatıldı'}
export default function SupportRequestsModule({supabase,profile,profiles}){
 const [rows,setRows]=useState([]),[selected,setSelected]=useState(null),[filter,setFilter]=useState('open'),[q,setQ]=useState(''),[busy,setBusy]=useState(false),[reply,setReply]=useState('')
 async function load(){const x=await supabase.from('support_requests').select('*').order('created_at',{ascending:false});setRows(x.data||[])}
 useEffect(()=>{load()},[])
 const visible=useMemo(()=>rows.filter(r=>(filter==='all'||(filter==='open'?!['resolved','closed'].includes(r.status):r.status===filter))&&(!q||[r.tracking_no,r.subject,r.description,r.complained_name].join(' ').toLocaleLowerCase('tr').includes(q.toLocaleLowerCase('tr')))),[rows,filter,q])
 const counts={new:rows.filter(x=>x.status==='new').length,work:rows.filter(x=>['reviewing','assigned'].includes(x.status)).length,private:rows.filter(x=>x.privacy_mode).length,done:rows.filter(x=>['resolved','closed'].includes(x.status)).length}
 async function patch(values){if(!selected)return;setBusy(true);await supabase.from('support_requests').update({...values,updated_at:new Date().toISOString()}).eq('id',selected.id);await supabase.from('support_request_audit').insert({request_id:selected.id,actor_profile_id:profile?.id,action:'update',new_value:values});setSelected({...selected,...values});await load();setBusy(false)}
 async function send(){if(!reply.trim())return;setBusy(true);await supabase.from('support_request_messages').insert({request_id:selected.id,author_profile_id:profile?.id,author_type:'management',body:reply.trim()});await patch({status:'answered'});setReply('');setBusy(false)}
 return <div className="supportHub"><div className="supportHero"><div><small>E-GÖLKENT · KURUMSAL İLETİŞİM</small><h2>Talep · Öneri · Şikâyet Yönetimi</h2><p>Başvuruları güvenli, kayıtlı ve sonuç odaklı biçimde yönetin.</p></div><b>YÖNETİM MERKEZİ</b></div><div className="supportStats"><div><b>{counts.new}</b><span>Yeni</span></div><div><b>{counts.work}</b><span>İşlemde</span></div><div><b>{counts.private}</b><span>Kimliği Gizli</span></div><div><b>{counts.done}</b><span>Sonuçlanan</span></div></div><div className="supportToolbar"><input placeholder="Takip no, konu veya içerik ara…" value={q} onChange={e=>setQ(e.target.value)}/><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="open">Açık Başvurular</option><option value="all">Tümü</option>{Object.entries(statuses).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div><div className="supportLayout"><div className="supportList">{!visible.length?<div className="supportEmpty">Henüz başvuru bulunmuyor.</div>:visible.map(r=><button key={r.id} className={'supportTicket '+(selected?.id===r.id?'active':'')} onClick={()=>setSelected(r)}><div><span>{types[r.request_type]}</span>{r.privacy_mode&&<em>🔒 Kimliği Gizli</em>}</div><b>{r.subject}</b><p>{r.description}</p><footer><span>{r.tracking_no}</span><strong>{statuses[r.status]}</strong><time>{new Date(r.created_at).toLocaleDateString('tr-TR')}</time></footer></button>)}</div><aside className="supportDetail">{!selected?<div className="supportEmpty">Detay için bir başvuru seçiniz.</div>:<><small>{selected.tracking_no}</small><h3>{selected.subject}</h3><div className="supportIdentity"><small>Başvuru</small><b>{selected.source_type==='parent'?'Veli Başvurusu':'Personel Başvurusu'}</b>{selected.privacy_mode&&<em>🔒 Kimliği gizli</em>}</div>{selected.request_type==='complaint'&&<div className="supportComplaint"><small>Şikâyet Edilen</small><b>{selected.complained_name||profiles.find(p=>p.id===selected.complained_profile_id)?.full_name||'Belirtilmedi'}</b></div>}<div className="supportBody">{selected.description}</div><div className="supportActions"><label>Durum<select value={selected.status} onChange={e=>patch({status:e.target.value})}>{Object.entries(statuses).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>İlgili Kişi<select value={selected.assigned_to||''} onChange={e=>patch({assigned_to:e.target.value||null,status:e.target.value?'assigned':selected.status})}><option value="">Atanmadı</option>{profiles.map(p=><option key={p.id} value={p.id}>{p.full_name}</option>)}</select></label></div><div className="supportReply"><textarea rows="4" placeholder="Başvuru sahibine cevap…" value={reply} onChange={e=>setReply(e.target.value)}/><button disabled={busy||!reply.trim()} onClick={send}>Cevabı Kaydet</button></div></>}</aside></div></div>
}