'use client'
import {useEffect,useState} from 'react'
export default function TeacherEvaluations({supabase,students,session}){
 const [studentId,setStudentId]=useState(''),[rows,setRows]=useState([]),[note,setNote]=useState(''),[category,setCategory]=useState('genel'),[visible,setVisible]=useState(true),[msg,setMsg]=useState('')
 async function load(id=studentId){if(!id)return setRows([]);const {data,error}=await supabase.from('parent_teacher_notes').select('*').eq('student_id',id).order('note_date',{ascending:false});if(error)setMsg(error.message);else setRows(data||[])}
 useEffect(()=>{if(studentId)load(studentId)},[studentId])
 async function save(e){e.preventDefault();const {error}=await supabase.from('parent_teacher_notes').insert({student_id:studentId,teacher_id:session.user.id,note_date:new Date().toISOString().slice(0,10),category,note,visible_to_parent:visible});if(error)return setMsg(error.message);setNote('');setMsg('Değerlendirme kaydedildi.');load()}
 async function remove(id){const {error}=await supabase.from('parent_teacher_notes').delete().eq('id',id);if(error)return setMsg(error.message);load()}
 return <section className="panel teacherEval"><div className="panelHead"><div><h3>Hoca Değerlendirmesi</h3><p>Öğrenci hakkında tarihli eğitim değerlendirmesi oluşturun ve veli görünürlüğünü belirleyin.</p></div></div><div className="filters"><select value={studentId} onChange={e=>setStudentId(e.target.value)}><option value="">Öğrenci seçiniz</option>{students.map(s=><option key={s.id} value={s.id}>{s.first_name} {s.last_name}</option>)}</select></div>{studentId&&<form className="institutionForm" onSubmit={save}><label>Kategori<select value={category} onChange={e=>setCategory(e.target.value)}><option value="genel">Genel</option><option value="ders">Ders</option><option value="ezber">Ezber</option><option value="devam">Devam / Gayret</option><option value="davranis">Davranış</option></select></label><label><input type="checkbox" checked={visible} onChange={e=>setVisible(e.target.checked)}/> Veli panelinde göster</label><label className="wide">Değerlendirme<textarea required value={note} onChange={e=>setNote(e.target.value)} placeholder="Öğrencinin eğitim süreci hakkında değerlendirme..."/></label><button className="primary">Değerlendirmeyi Kaydet</button></form>}{msg&&<div className="msg">{msg}</div>}{studentId&&<div className="tableWrap"><table><thead><tr><th>Tarih</th><th>Kategori</th><th>Değerlendirme</th><th>Veli</th><th></th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.note_date}</td><td>{r.category}</td><td>{r.note}</td><td>{r.visible_to_parent?'Gösteriliyor':'Gizli'}</td><td><button className="ghost" onClick={()=>remove(r.id)}>Sil</button></td></tr>)}{!rows.length&&<tr><td colSpan="5">Henüz değerlendirme yok.</td></tr>}</tbody></table></div>}</section>
}