'use client'
import {useEffect,useMemo,useState} from 'react'
export default function YuzuneMatrix({supabase,students,classes,institution,profile}){
 const [items,setItems]=useState([]),[rows,setRows]=useState([]),[classId,setClassId]=useState(''),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[newTitle,setNewTitle]=useState(''),[busy,setBusy]=useState(false)
 const yuzClasses=classes.filter(c=>c.program==='yuzune'),manager=['admin','super_admin'].includes(profile?.role)
 const list=useMemo(()=>students.filter(s=>s.status==='active'&&(!classId||s.class_id===classId)&&(classId||yuzClasses.some(c=>c.id===s.class_id))).sort((a,b)=>(a.first_name+' '+a.last_name).localeCompare(b.first_name+' '+b.last_name,'tr')),[students,classId,classes])
 async function load(){const [{data:i},{data:r}]=await Promise.all([supabase.from('yuzune_curriculum_items').select('*').eq('institution_id',institution.id).eq('active',true).order('sort_order'),supabase.from('yuzune_progress').select('*')]);setItems(i||[]);setRows(r||[])}
 useEffect(()=>{if(institution?.id)load()},[institution?.id])
 const get=(sid,iid)=>rows.find(r=>r.student_id===sid&&r.item_id===iid)
 async function result(sid,iid,value){setBusy(true);const old=get(sid,iid);if(!value){if(old)await supabase.from('yuzune_progress').delete().eq('id',old.id)}else await supabase.from('yuzune_progress').upsert({student_id:sid,item_id:iid,result:value,quality:value==='plus'?old?.quality||null:null,lesson_date:date,recorded_by:profile.id},{onConflict:'student_id,item_id'});await load();setBusy(false)}
 async function quality(sid,iid,value){const old=get(sid,iid);if(!old||old.result!=='plus')return;setBusy(true);await supabase.from('yuzune_progress').update({quality:value||null,lesson_date:date,recorded_by:profile.id,updated_at:new Date().toISOString()}).eq('id',old.id);await load();setBusy(false)}
 async function addItem(){if(!newTitle.trim())return;setBusy(true);await supabase.from('yuzune_curriculum_items').insert({institution_id:institution.id,title:newTitle.trim(),sort_order:(items.at(-1)?.sort_order||0)+1,created_by:profile.id});setNewTitle('');await load();setBusy(false)}
 return <div className="yuzMatrixPage"><div className="matrixHero"><div><small>E-GÖLKENT · YÜZÜNE EĞİTİM TAKİBİ</small><h2>Yüzüne Ders Cetveli</h2><p>Birinci satır ders sonucu (+/−), ikinci satır kalite (S/İ/O/Z). Ders sütunları arasında sıra zorunluluğu yoktur.</p></div><div className="matrixFilters"><select value={classId} onChange={e=>setClassId(e.target.value)}><option value="">Tüm Yüzüne Sınıfları</option>{yuzClasses.map(c=><option value={c.id} key={c.id}>{c.code} — {c.name}</option>)}</select><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></div></div>
 {manager&&<div className="matrixAdmin"><b>Ders Sütunu Ekle</b><input value={newTitle} onChange={e=>setNewTitle(e.target.value)} placeholder="Örn. Yasin 7"/><button className="primary" onClick={addItem} disabled={busy}>+ Sütun Ekle</button></div>}
 <div className="matrixLegend"><span><b>+</b> Ders verdi</span><span><b>−</b> Ders vermedi / tekrar</span><span className="lg saglam">S Sağlam</span><span className="lg iyi">İ İyi</span><span className="lg orta">O Orta</span><span className="lg zayif">Z Zayıf</span></div>
 <div className="matrixWrap"><table className="yuzMatrix"><thead><tr><th className="stickyStudent">Öğrenci</th>{items.map(i=><th key={i.id}><span>{i.title}</span></th>)}</tr></thead><tbody>{list.map((st,n)=><tr key={st.id}><td className="stickyStudent"><b>{n+1}</b><span>{st.first_name} {st.last_name}</span></td>{items.map(i=>{const r=get(st.id,i.id);return <td key={i.id} className={r?.quality||''}><div className="matrixCell"><select value={r?.result||''} onChange={e=>result(st.id,i.id,e.target.value)} disabled={busy}><option value="">·</option><option value="plus">+</option><option value="minus">−</option></select><select value={r?.quality||''} onChange={e=>quality(st.id,i.id,e.target.value)} disabled={busy||r?.result!=='plus'}><option value="">·</option><option value="saglam">S</option><option value="iyi">İ</option><option value="orta">O</option><option value="zayif">Z</option></select></div></td>})}</tr>)}</tbody></table></div>
 <p className="matrixNote">Kalite satırı yalnızca üst satırda <b>+</b> seçildiğinde açılır. Öğrenci bugün Sübhaneke, başka bir gün Yasin veya herhangi başka bir sütundan ders verebilir.</p></div>
}