'use client'
import useLiveRefresh from '../hooks/useLiveRefresh'
import {useEffect,useMemo,useState} from 'react'
export default function YuzuneMatrix({supabase,students,classes,institution,profile,permissions}){
 const canCreate=profile?.role==='super_admin'||!!permissions?.can_create,canUpdate=profile?.role==='super_admin'||!!permissions?.can_update,canDelete=profile?.role==='super_admin'||!!permissions?.can_delete
 const [opClasses,setOpClasses]=useState([]),[scopeReady,setScopeReady]=useState(false)
 const [items,setItems]=useState([]),[rows,setRows]=useState([]),[classId,setClassId]=useState(''),[date,setDate]=useState(new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Istanbul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())),[newTitle,setNewTitle]=useState(''),[newPosition,setNewPosition]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false)
 const yuzClasses=classes.filter(c=>c.program==='yuzune'),manager=['admin','super_admin'].includes(profile?.role)
 const list=useMemo(()=>students.filter(s=>(s.student_status||s.status)==='active'&&(!classId||s.class_id===classId)&&(classId||yuzClasses.some(c=>c.id===s.class_id))).sort((a,b)=>(a.first_name+' '+a.last_name).localeCompare(b.first_name+' '+b.last_name,'tr')),[students,classId,classes])
 async function load(){const [{data:i},{data:r}]=await Promise.all([supabase.from('yuzune_curriculum_items').select('*').eq('institution_id',institution.id).eq('active',true).order('sort_order'),supabase.from('yuzune_progress').select('*').in('student_id',students.map(s=>s.id).filter(Boolean))]);setItems(i||[]);setRows(r||[])}
 useEffect(()=>{if(institution?.id)load()},[institution?.id])
 useEffect(()=>{if(!profile?.id)return;setScopeReady(false);if(profile?.role==='super_admin'){setOpClasses(classes.filter(c=>c.program==='yuzune').map(c=>c.id));setScopeReady(true);return}Promise.all(classes.filter(c=>c.program==='yuzune').map(async c=>{const {data}=await supabase.rpc('can_operate_class',{p_class_id:c.id,p_module:'yuzune'});return data?c.id:null})).then(x=>{setOpClasses(x.filter(Boolean));setScopeReady(true)})},[profile?.id,classes,permissions])
 useLiveRefresh(supabase,['yuzune_curriculum_items','yuzune_progress'],load)
 const get=(sid,iid)=>rows.find(r=>r.student_id===sid&&r.item_id===iid)
 async function result(sid,iid,value){const st=students.find(s=>s.id===sid);if(!canUpdate||!opClasses.includes(st?.class_id)){setNotice('Bu işlem için düzenleme yetkiniz bulunmuyor.');return}setBusy(true);const {error}=await supabase.rpc('set_yuzune_result',{p_student:sid,p_item:iid,p_result:value||null,p_date:date});if(error){setNotice('İşlem kaydedilemedi: '+error.message);setBusy(false);return}setNotice('');await load();setBusy(false)}
 async function quality(sid,iid,value){const st=students.find(s=>s.id===sid);if(!canUpdate||!opClasses.includes(st?.class_id)){setNotice('Bu işlem için düzenleme yetkiniz bulunmuyor.');return}const old=get(sid,iid);if(!old||old.result!=='plus')return;setBusy(true);const {error}=await supabase.from('yuzune_progress').update({quality:value||null,lesson_date:date,recorded_by:profile.id,updated_at:new Date().toISOString()}).eq('id',old.id);if(error){setNotice('Kalite kaydedilemedi: '+error.message);setBusy(false);return}setNotice('');await load();setBusy(false)}
 async function addItem(){if(!canCreate){setNotice('Bu işlem için ekleme yetkiniz bulunmuyor.');return}if(!newTitle.trim()){setNotice('Ders sütunu adını yazınız.');return}setBusy(true);setNotice('');const {error}=await supabase.rpc('add_yuzune_curriculum_item',{p_institution:institution.id,p_title:newTitle.trim(),p_position:newPosition?Number(newPosition):null});if(error)setNotice('Eklenemedi: '+error.message);else{setNotice('Ders sütunu eklendi.');setNewTitle('');setNewPosition('');await load()}setBusy(false)}
 async function deleteItem(item){if(!canDelete){setNotice('Bu işlem için silme yetkiniz bulunmuyor.');return}if(!confirm('“'+item.title+'” sütununu silmek istediğinize emin misiniz? Öğrenci geçmiş kayıtları korunacaktır.'))return;setBusy(true);setNotice('');const {error}=await supabase.rpc('delete_yuzune_curriculum_item',{p_item:item.id});if(error)setNotice('Sütun silinemedi: '+error.message);else{setNotice('“'+item.title+'” sütunu silindi.');await load()}setBusy(false)}
 async function moveItem(id,pos){if(!canUpdate){setNotice('Bu işlem için düzenleme yetkiniz bulunmuyor.');return}setBusy(true);setNotice('');const {error}=await supabase.rpc('move_yuzune_curriculum_item',{p_item:id,p_position:Number(pos)});if(error)setNotice('Sıralama değiştirilemedi: '+error.message);else{setNotice('Sütun sırası güncellendi.');await load()}setBusy(false)}
 return <div className="yuzMatrixPage"><div className="matrixHero"><div><small>E-GÖLKENT · YÜZÜNE EĞİTİM TAKİBİ</small><h2>Yüzüne Ders Cetveli</h2><p>Birinci satır ders sonucu (+/−), ikinci satır kalite (S/İ/O/Z). Ders sütunları arasında sıra zorunluluğu yoktur.</p></div><div className="matrixFilters"><select value={classId} onChange={e=>setClassId(e.target.value)}><option value="">Tüm Yüzüne Sınıfları</option>{yuzClasses.map(c=><option value={c.id} key={c.id}>{c.code} — {c.name}</option>)}</select><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></div></div>
 {manager&&<div className="matrixAdmin"><b>Ders Sütunu Ekle</b><input value={newTitle} onChange={e=>setNewTitle(e.target.value)} placeholder="Örn. Yasin 7"/><input className="matrixOrderInput" type="number" min="1" max={items.length+1} value={newPosition} onChange={e=>setNewPosition(e.target.value)} placeholder={"Sıra (1-"+(items.length+1)+")"}/><button className="primary" onClick={addItem} disabled={busy}>+ Sütun Ekle</button>{notice&&<span className="matrixNotice">{notice}</span>}</div>}
 <div className="matrixLegend"><span><b>+</b> Ders verdi</span><span><b>−</b> Ders vermedi / tekrar</span><span className="lg saglam">S Sağlam</span><span className="lg iyi">İ İyi</span><span className="lg orta">O Orta</span><span className="lg zayif">Z Zayıf</span></div>
 <div className="matrixWrap"><table className="yuzMatrix"><thead><tr><th className="stickyStudent">Öğrenci</th>{items.map((i,index)=><th key={i.id}><div className="columnHead"><span className="columnTitle">{i.title}</span>{manager&&<div className="columnTools"><select className="columnOrder" value={index+1} onChange={e=>moveItem(i.id,e.target.value)} disabled={busy}>{items.map((_,n)=><option key={n} value={n+1}>{n+1}</option>)}</select><button className="columnDelete" title={i.title+" sütununu sil"} onClick={()=>deleteItem(i)} disabled={busy} aria-label={i.title+" sütununu sil"}>×</button></div>}</div></th>)}</tr></thead><tbody>{list.map((st,n)=><tr key={st.id}><td className="stickyStudent"><b>{n+1}</b>{st.photo_url?<img className="lessonStudentPhoto" src={st.photo_url} alt="" />:<span className="lessonStudentPhoto lessonStudentInitial">{(st.first_name||'?').charAt(0)}</span>}<span>{st.first_name} {st.last_name}</span></td>{items.map(i=>{const r=get(st.id,i.id);return <td key={i.id} className={r?.quality||''}><div className="matrixCell"><select value={r?.result||''} onChange={e=>result(st.id,i.id,e.target.value)} disabled={busy||!scopeReady||!opClasses.includes(st.class_id)}><option value="">·</option><option value="plus">+</option><option value="minus">−</option></select><select value={r?.quality||''} onChange={e=>quality(st.id,i.id,e.target.value)} disabled={busy||!scopeReady||!opClasses.includes(st.class_id)||r?.result!=='plus'}><option value="">·</option><option value="saglam">S</option><option value="iyi">İ</option><option value="orta">O</option><option value="zayif">Z</option></select></div></td>})}</tr>)}</tbody></table></div>
 <p className="matrixNote">Kalite satırı yalnızca üst satırda <b>+</b> seçildiğinde açılır. Öğrenci bugün Sübhaneke, başka bir gün Yasin veya herhangi başka bir sütundan ders verebilir.</p></div>
}