'use client'
import {useEffect,useMemo,useState} from 'react'
export default function YuzuneMatrix({supabase,students,classes,institution,profile}){
 const [items,setItems]=useState([]),[rows,setRows]=useState([]),[classId,setClassId]=useState(''),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[newTitle,setNewTitle]=useState(''),[newPosition,setNewPosition]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false)
 const yuzClasses=classes.filter(c=>c.program==='yuzune'),manager=['admin','super_admin'].includes(profile?.role)
 const list=useMemo(()=>students.filter(s=>s.status==='active'&&(!classId||s.class_id===classId)&&(classId||yuzClasses.some(c=>c.id===s.class_id))).sort((a,b)=>(a.first_name+' '+a.last_name).localeCompare(b.first_name+' '+b.last_name,'tr')),[students,classId,classes])
 async function load(){const [{data:i},{data:r}]=await Promise.all([supabase.from('yuzune_curriculum_items').select('*').eq('institution_id',institution.id).eq('active',true).order('sort_order'),supabase.from('yuzune_progress').select('*')]);setItems(i||[]);setRows(r||[])}
 useEffect(()=>{if(institution?.id)load()},[institution?.id])
 const get=(sid,iid)=>rows.find(r=>r.student_id===sid&&r.item_id===iid)
 async function result(sid,iid,value){setBusy(true);const old=get(sid,iid);if(!value){if(old)await supabase.from('yuzune_progress').delete().eq('id',old.id)}else await supabase.from('yuzune_progress').upsert({student_id:sid,item_id:iid,result:value,quality:value==='plus'?old?.quality||null:null,lesson_date:date,recorded_by:profile.id},{onConflict:'student_id,item_id'});await load();setBusy(false)}
 async function quality(sid,iid,value){const old=get(sid,iid);if(!old||old.result!=='plus')return;setBusy(true);await supabase.from('yuzune_progress').update({quality:value||null,lesson_date:date,recorded_by:profile.id,updated_at:new Date().toISOString()}).eq('id',old.id);await load();setBusy(false)}
 async function addItem(){if(!newTitle.trim()){setNotice('Ders sütunu adını yazınız.');return}setBusy(true);setNotice('');const {error}=await supabase.rpc('add_yuzune_curriculum_item',{p_institution:institution.id,p_title:newTitle.trim(),p_position:newPosition?Number(newPosition):null});if(error)setNotice('Eklenemedi: '+error.message);else{setNotice('Ders sütunu eklendi.');setNewTitle('');setNewPosition('');await load()}setBusy(false)}
 async function deleteItem(item){if(!confirm('“'+item.title+'” sütununu silmek istediğinize emin misiniz? Öğrenci geçmiş kayıtları korunacaktır.'))return;setBusy(true);setNotice('');const {error}=await supabase.rpc('delete_yuzune_curriculum_item',{p_item:item.id});if(error)setNotice('Sütun silinemedi: '+error.message);else{setNotice('“'+item.title+'” sütunu silindi.');await load()}setBusy(false)}
 async function moveItem(id,pos){setBusy(true);setNotice('');const {error}=await supabase.rpc('move_yuzune_curriculum_item',{p_item:id,p_position:Number(pos)});if(error)setNotice('Sıralama değiştirilemedi: '+error.message);else{setNotice('Sütun sırası güncellendi.');await load()}setBusy(false)}
 return <div className="yuzMatrixPage"><div className="matrixHero"><div><small>E-GÖLKENT · YÜZÜNE EĞİTİM TAKİBİ</small><h2>Yüzüne Ders Cetveli</h2><p>Birinci satır ders sonucu (+/−), ikinci satır kalite (S/İ/O/Z). Ders sütunları arasında sıra zorunluluğu yoktur.</p></div><div className="matrixFilters"><select value={classId} onChange={e=>setClassId(e.target.value)}><option value="">Tüm Yüzüne Sınıfları</option>{yuzClasses.map(c=><option value={c.id} key={c.id}>{c.code} — {c.name}</option>)}</select><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></div></div>
 {manager&&<div className="matrixAdmin"><b>Ders Sütunu Ekle</b><input value={newTitle} onChange={e=>setNewTitle(e.target.value)} placeholder="Örn. Yasin 7"/><input className="matrixOrderInput" type="number" min="1" max={items.length+1} value={newPosition} onChange={e=>setNewPosition(e.target.value)} placeholder={"Sıra (1-"+(items.length+1)+")"}/><button className="primary" onClick={addItem} disabled={busy}>+ Sütun Ekle</button>{notice&&<span className="matrixNotice">{notice}</span>}</div>}
 <div className="matrixLegend"><span><b>+</b> Ders verdi</span><span><b>−</b> Ders vermedi / tekrar</span><span className="lg saglam">S Sağlam</span><span className="lg iyi">İ İyi</span><span className="lg orta">O Orta</span><span className="lg zayif">Z Zayıf</span></div>
 <div className="matrixWrap"><table className="yuzMatrix"><thead><tr><th className="stickyStudent">Öğrenci</th>{items.map((i,index)=><th key={i.id}><div className="columnHead"><span className="columnTitle">{i.title}</span>{manager&&<div className="columnTools"><select className="columnOrder" value={index+1} onChange={e=>moveItem(i.id,e.target.value)} disabled={busy}>{items.map((_,n)=><option key={n} value={n+1}>{n+1}</option>)}</select><button className="columnDelete" title={i.title+" sütununu sil"} onClick={()=>deleteItem(i)} disabled={busy} aria-label={i.title+" sütununu sil"}>×</button></div>}</div></th>)}</tr></thead><tbody>{list.map((st,n)=><tr key={st.id}><td className="stickyStudent"><b>{n+1}</b><span>{st.first_name} {st.last_name}</span></td>{items.map(i=>{const r=get(st.id,i.id);return <td key={i.id} className={r?.quality||''}><div className="matrixCell"><select value={r?.result||''} onChange={e=>result(st.id,i.id,e.target.value)} disabled={busy}><option value="">·</option><option value="plus">+</option><option value="minus">−</option></select><select value={r?.quality||''} onChange={e=>quality(st.id,i.id,e.target.value)} disabled={busy||r?.result!=='plus'}><option value="">·</option><option value="saglam">S</option><option value="iyi">İ</option><option value="orta">O</option><option value="zayif">Z</option></select></div></td>})}</tr>)}</tbody></table></div>
 <p className="matrixNote">Kalite satırı yalnızca üst satırda <b>+</b> seçildiğinde açılır. Öğrenci bugün Sübhaneke, başka bir gün Yasin veya herhangi başka bir sütundan ders verebilir.</p></div>
}